### ISSUE TITLE
A vision for CodiMD

### ISSUE THREAD

**Issue by SISheogorath** [codimd/server#10]
Here we are! [CodiMD is running in an own organization](https://github.com/codimd). Hard forking is usually the last resort for an open source project, but we felt that it was neccessary for continued development and the future of CodiMD. If you wish to read up on the final debate that lead to this, [please refer to the old bug tracker](https://github.com/hackmdio/codimd/issues/1170).

It's time to stand together and find our way through the jungle. In some regards, we are back to zero, and that's sad. But on the bright side, the issue tracker has a lot room for your problems! :tada:

Let's work together!

The new GitHub organization provides us with all the flexibility we need to work on our own terms. We already sent out invitations to various community project participants and will welcome people to [join us](https://riot.im/app/#/room/#codimd:matrix.org).

You might wonder about the next steps. We currently rebuild the infrastructure parts that were in the hands of HackMD, like the [container repository](https://quay.io/repository/codimd/server?tab=tags), and work on integrating services with our new home, which was previously more difficult.

With this done, we look towards a very interesting future:

One of the first actions we'll take is providing a fully documented and working API for CodiMD, which should allow you to import, export, create, delete and even modify your notes. You are welcome to participate in the debate about the API design.

APIs are great, but your eyes deserve some love, too: So we also started working on some UI/UX improvements. User Profiles will be continued and completed over here.

Finally, we also want to work on improving the connections and collaboration within the community. Our [community forum](https://community.codimd.org) ~~should be up in a few days~~ is up.

I'm looking forward to your ideas, inspiration and comments. Let everyone know, that CodiMD is not dead, it's reborn!

**Comment by SISheogorath** [comment]
QA
---

### Do I need to change anything to run the new version?

Yes, you might need some changes for your next update.

**Native setup using git:**

Change the upstream remote using `git remote set-url origin https://github.com/codimd/server.git`.

**Docker:**

When you use our [container repository](https://github.com/codimd/container)  (which was previously `codimd-container`) all you can simply run `git pull` and your `docker-compose.yml` will be updated.

When you setup things yourself, make sure you use the new image: [`quay.io/codimd/server`](https://quay.io/repository/codimd/server?tab=tags).

**Heroku:**

All you need to do is [disconnect GitHub](https://devcenter.heroku.com/articles/github-integration#disconnecting-from-github) and [reconnect it](https://devcenter.heroku.com/articles/github-integration#enabling-github-integration) with this new repository.

Or you can use our Heroku button and redeploy your instance and just link the old database again.

### Do I need to change anything when I was using the codimd-cli or codimd-container repository?

No, those repositories were moved. This means github takes care. But feel free to use `git remote set-url origin https://github.com/codimd/cli.git` and `git remote set-url origin https://github.com/codimd/container.git`

### What happens to the old repository?

We don't know. This is no longer in our hands, but we wish for the best.

**Comment by gramakri** [comment]
Just learnt about this big change, thanks for continuing this work! From the Cloudron side, the [CodiMD app](https://cloudron.io/store/io.hackmd.cloudronapp.html) will continue to follow this repo. We had already changed the name a few releases ago - [this commit](https://git.cloudron.io/cloudron/codimd-app/commit/6d8049db496830583821960310e7fb055fa5c127). I am just fixing up our package to use the new 1.3.2 release that was made some hours ago.

**Comment by MartB** [comment]
Whats up with the other organisation?
Why are there frequent updates atm i thought its abandoned?

**Comment by SISheogorath** [comment]
@MartB The old repository is continued by the original HackMD team, according to [their statement](https://github.com/hackmdio/codimd/issues/1170#issuecomment-477718380). There is currently not so much activity over here, because I'm quite busy right now, but will dedicate some more time to it in September. Every contribution is very welcome and I'll take some time to review it, when they come it and also try to merge things. It's just that I have no time right now to write own features.

**Comment by zeigerpuppy** [comment]
Viva the open CodiMD.

One thought, would it make sense for us to have the project in a Gitlab repository rather than Github?  It may be the only chance to make that change.

It just seems more natural to have the project live on a Gitlab repo considering that CodiMD integrates so well with the other components of that ecosystem.

If there's support for a shift, I'd be happy to provide hosting resources if they're needed.

**Comment by HerHde** [comment]
@zeigerpuppy Great idea, but that was [discussed earlier](https://github.com/hackmdio/codimd/issues/838), when MS acquired GH. The voting result was quite even.

Though I guess there are a lot of GitLab CE users, hosters and fans here, including Sheo and Claudius (and even my humble self), Claudius [politely declined](https://github.com/hackmdio/codimd/issues/838#issuecomment-400761435) that proposal when I offered it.

**Comment by zeigerpuppy** [comment]
@HerHde Thanks for pointing me to the discussion.  And a reasonable outcome for the moment too.

**Comment by SuperSandro2000** [comment]
GitLab has no discovery so we would lose on a lot of potential new users and they would probably just find the codimd of hackmd.

**Comment by almereyda** [comment]
We are using GitLab's "repository mirroring" functionality to keep issues
and MRs in GitLab, and push changes to GitHub on any push. That also allows
us to integrate with the automatic Docker Hub pipeline.

So we use GitHub for visibility and discovery, and GitLab for work.

Ref.:

- https://lab.allmende.io/wirvsvirus/lefat/lefat-backend
- https://lab.allmende.io/wirvsvirus/lefat/lefat-frontend

- https://github.com/lefat/lefat-backend
- https://github.com/lefat/lefat-frontend

**Comment by zeigerpuppy** [comment]
That's great to see, and thanks for the remindier about the repository mirroring feature, really useful for us lovers of GitLab!

**Comment by SISheogorath** [comment]
So I wanted to give everyone some space to express their opinion before I jumps Ingo this discussion, because as maintainer it might stops some people from expressing themselves when they already see "there seems to be a official decision".

As some people might know, I'm definitely in favor of self-hosted solutions, BUT as we already mentioned in the previous repository, we should look at what suites out community best. Right now, the influx of new people seems quite good and people seem to enjoy hanging out here. I would like to avoid breaking that. And given that we will also rename in a foreseeable future it'll make a lot of things more difficult when we also change the repository at the same time. (Not to mention that GitLab really isn't great for SEO, sadly)

On the other hand there is the hybrid approach that @almereyda mentioned, but that opens a bunch of problems. Gitlab CE is not made for fork/edit/MR workflows. You neither get CI runs in your own namespace for a MR of a fork, nor do you get a MR for the actual merged version. Which makes it much more complicated to asses if merging something will break your master branch.

All in all, what speaks for hosting it off GitHub:

- We could use free software
- We might enable people who refuse to use GitHub to contribute
- we wouldn't have downtimes when GitHub is down

What speaks against it:

- We would lose a lot of SEO
- We would break the current influx of new contributors (most likely)
- We would increase the complication of contribution by requiring new accounts
- The CI features wouldn't fit our development workflow

Exception: Sourcehut.
Here the requirement of an account could be removed, but it would force us into a Mailinglist-based development workflow which I don't think people would be willing to do.

I'm very open for critique of my just wrote together piece, because maybe I have a complete misassumption of what is going on.

**Comment by zeigerpuppy** [comment]
@SISheogorath really good points.
From my perspective if a project can be done with free software it's always a bonus.  I guess the situation with GitLab/CodiMD is also a special case.  It would mean we could use the GitLab/Mattermost/CodiMD integration in the process of further development (which may also lead to new use cases and tighter interoperability).
But I don't believe in changing platforms if it means that the workflow will be much more difficult.  Ultimately I think that's a decision for the key maintainers.

Losing SEO and discoverability are certainly big issues.
But the main issue you've raised of the different merge workflow seems to be an even bigger problem.  I didn't realise that GitLab was so different in that regard.

**Comment by pirate** [comment]
FWIW, I would be unlikely to contribute to a GitLab based development workflow simply because I never interact with that site, and most of my interaction with CodiMD happens organically on Github when I notice I have notifications. I suspect this is also the case for many other casual CodiMD contributors over the years.  I'm by no means a core contributor to CodiMD, so don't let me sway the overall opinion much, but I do want to contribute myself as a datapoint in the overall discussion.

**Comment by ccoenen** [comment]
I'm very torn on this one. On the one hand, we're creating a huge single point of failure with a centralised entity. On the other hand, I do also _like_ the benefits a one-stop-shop like Github or Gitlab brings. I still have ~50 accounts on various bug trackers and forums from ye'olde times when every project did this for themselves. That was no fun at all. I rarely go to these lengths today, to be honest.

So, there I have it. Complete conflict of What I *want* to have and what I *actually* do. 😕

**Comment by ccoenen** [comment]
Single point of failure in my post above refers to multiple things. I'm not only talking about "github might go down", but also to the way they do business, the rules they enforce, the general power they have over open source, just by basically enabling or disabling whatever or whoever they want.

**Comment by SISheogorath** [comment]
With the HedgeDoc renaming on the horizon and further work towards 2.0, I think we can close this in favour of the [big orga board](https://github.com/orgs/codimd/projects/1) for 2.0 which will summarize and show way better what HedgeDoc will become. :slightly_smiling_face:
