### ISSUE TITLE
Support for abbreviations

### ISSUE THREAD

**Issue by Amolith** [codimd/server#100]
I've started using [Joplin](https://joplinapp.org/) for todo lists, note taking, etc. and it has a feature I would really like to see in CodiMD. You can do abbreviations for words that, when hovered over, display the expanded term. The syntax is just `* [TermAbbr]: Expanded term` and it goes on a line near the bottom. Any time `TermAbbr` shows up in the parsed document, it has a wavy underline and, when hovered over, displays `Expanded term`.

![image](https://user-images.githubusercontent.com/29460675/58772743-3ef80980-8588-11e9-802f-8c7876354d66.png)

It's part of the [markdown-it](https://github.com/markdown-it/markdown-it) parser and they have a [demo website](https://markdown-it.github.io/) you can look at.  The abbreviations portion is at the very bottom.

**Comment by SISheogorath** [comment]
It seems like there is just documentation missing on the features page:

https://demo.codimd.org/Ip0p_gdrQ-ytfTNab2BjXQ#

Feel free to put it [there](https://github.com/codimd/server/blob/master/public/docs/features.md) :)

**Comment by fbartels** [comment]
But the example is already on the features page (and with a much nicer english as well) -> https://github.com/codimd/server/blob/master/public/docs/features.md#abbreviations

**Comment by SISheogorath** [comment]
Huh, good point @fbartels! Then ehh @Amolith what do you propose here? Maybe it's a misunderstanding?

**Comment by Amolith** [comment]
Well . . . you happen to be correct 😆  markdown-it uses a space after the * and I tried that without success but didn't think to search the features page.

Thank you for pointing that out @fbartels 😅
