### ISSUE TITLE
Subdomain

### ISSUE THREAD

**Issue by AndiLeni** [codimd/server#102]
Hello,
I installed codimd to run under a subdomain. It is working fine so far, but when I access my other domains and Subdomains they also show my the codimd frontpage. 
What can cause this issue?

Regards
Andi

**Comment by SISheogorath** [comment]
Sounds like a misconfigured reverse proxy, please check your nginx or apache2 settings.

**Comment by AndiLeni** [comment]
Your were right. It was a problem with my server configuration.
