### ISSUE TITLE
Is `CMD_URL_PATH` working at the moment?

### ISSUE THREAD

**Issue by CHBMB** [codimd/server#105]
I'm trying (unsuccessfully) to get CodiMD served up at `https://server.com/codimd` 

I'm wondering a couple of things as I peruse the docs and issues.  Firstly am I doing something wrong?  I'm starting CodiMD with the following variables.
```
CMD_DOMAIN=server.com
CMD_PROTOCOL_USESSL=true
CMD_URL_PATH=codimd
```
Secondly is it possibly broken at the moment?
I normally assume I'm doing something wrong, but I came across this [commit](https://github.com/hackmdio/codimd/pull/932/commits/6056f9a392c27defafebdac2816b5dcf5f30eb91) from this [issue](https://github.com/hackmdio/codimd/issues/424#issuecomment-490721855) so I just wondered if anyone could clarify?

I have successfully deployed CodiMD using a dedicated subdomain on `codimd.server.com` without any issues.

Thanks!

**Comment by SISheogorath** [comment]
Yes, that's correct, this feature is currently broken and someone no one had the time/interest to fix it yet.

Personally I'm considering to just drop it, as I think it's reasonable in 2019 to use an own subdomain for CodiMD especially when you consider the attack vectors that appear when using the same FQDN for multiple services. (i.e. breaking same origin policies, CSPs, …)

I don't recommend those path based setups.

**Comment by CHBMB** [comment]
@SISheogorath Fair enough, as long as I know it's not a PEBKAC error that's fine.  :grin:
