### ISSUE TITLE
night mode does not shade some view mode buttons

### ISSUE THREAD

**Issue by stragu** [codimd/server#11]
Hi all! Thanks for your amazing work :)

There's an issue with the night mode: two out of three view mode buttons do not use a darker colour when selected (the buttons right next to "CodiMD" in the toolbar). "View" does have a darker colour when pressed, as expected, but "Both" and "Edit" don't. (Actually, when looking very closely, there is a slight difference but it is barely noticeable.)

I am using demo.codimd.org.

Cheers

(copied from the [old repo's issue](https://github.com/hackmdio/codimd/issues/1183))

**Comment by SISheogorath** [comment]
Fixed by 9941d5613b2832835a71f8ed6cd1c5ab3629e5f5

**Comment by stragu** [comment]
Quickest bugfix I've ever seen! :tada:
