### ISSUE TITLE
Swedish locale creates internal server error

### ISSUE THREAD

**Issue by ccoenen** [codimd/server#117]
this is related to https://github.com/hackmdio/codimd/issues/1222

Steps to reproduce:

* Go to https://demo.codimd.org (switch to intro tab if logged in!)
* Switch your locale in the locale dropdown, choose "Svenska"
* Go to any pad, for example https://demo.codimd.org/features

You'll receive an internal server error.

**Comment by ccoenen** [comment]
This is probably caused by a typo in the locale:

https://github.com/codimd/server/blob/master/locales/sv.json#L65

note the extra space in `% s`. I already corrected this on POEditor.

**Comment by SISheogorath** [comment]
Fixed in 8612740f828a25a00df3aa5a16a9f9976f9d4a69
