### ISSUE TITLE
Enable the Wiki

### ISSUE THREAD

**Issue by gramakri** [codimd/server#12]
It looks like the wiki for this repo is disabled or empty? When I click it, nothing happens. Would it be possible to enable it?

Maybe we can just clone https://github.com/hackmdio/codimd.wiki.git and push it here for a start. It has some important pages like https://github.com/hackmdio/codimd/wiki/Environment-Variables

**Comment by ccoenen** [comment]
Thank you for bringing this up! I have to admint that I didn't even remember there were wiki pages in the old repository. We currently have two locations for documentation, apparently. There's also a `/docs` directory in this repository.

My plan for the next few days would have been to restructure the README anyway. I would also import the previous wiki pages into that docs folder. This will be linked to from the README, so it is as easy to notice as the github wiki.

Would this be satisfactory to you?

**Comment by gramakri** [comment]
@ccoenen Yes, that will be awesome to have them all merged. I don't particularly care if the wiki itself is there or if `/docs` is used and linked from README as long as the information survives.

**Comment by SISheogorath** [comment]
I just opened the Wiki for everyone to edit things.

But I would prefer when all documentation will go into `./docs` while the wiki can be a community playground. For example to make a list of instances that are out there open for the public (like it existed in the old wiki) as well as tips and tricks on how to use CodiMD :)

Be creative!

**Comment by ccoenen** [comment]
I just merged #15 which brought over all infos from the previous wiki (except the list of instances). The wiki in here has been modified to point to that docs directory.

I would suggest that we use markdown-files in `/docs` for all things that belong with the code. But if there's anything that would be better held in the wiki (like a list of instances), feel free to add it!

**Comment by Perflyst** [comment]
> I just opened the Wiki for everyone to edit things.

It is not open for edits (at least I cant edit it). I wanted to transfer the old list from here https://github.com/hackmdio/codimd/wiki/CodiMD-Instances

**Comment by ccoenen** [comment]
there was an additional setting that I didn't know about. It should be editable, now.

![restrict wiki access setting](https://user-images.githubusercontent.com/124909/60389787-a7270600-9ac8-11e9-9cbe-636f5299e21b.png)
