### ISSUE TITLE
Latex export PDF

### ISSUE THREAD

**Issue by AndiLeni** [codimd/server#131]
I noticed, that latex expressions are rendered as plain text when I try to export as pdf, which is probably a bug.

Reproduce:
````
Chomsky Normalform:
- $A \rightarrow a, a \in \Sigma$
- $A \rightarrow BC, BC \in V$
````

Output in PDF:
![grafik](https://user-images.githubusercontent.com/13385771/60664963-81508700-9e63-11e9-8e7f-a4a6bc413135.png)

**Comment by davidmehren** [comment]
As we had to disable the PDF export feature for security reasons, I'm going to close this now. If we reimplement this feature in the future, correctly exporting LaTeX will probably be a requirement anyway.

**Comment by rikmendes** [comment]
> As we had to disable the PDF export feature for security reasons, I'm going to close this now. If we reimplement this feature in the future, correctly exporting LaTeX will probably be a requirement anyway.

Is there any chance PDF export would return, even more for a login based codiMD ?
![image](https://user-images.githubusercontent.com/12155003/96864585-a55c2100-1436-11eb-9002-ddfbf4525c9e.png)
