### ISSUE TITLE
404 Not Found 

### ISSUE THREAD

**Issue by kroschu** [codimd/server#132]
When i try to type cyrillic letters i receive this error. I use LinuxServer.io CodiMD docker Image.

**Comment by ccoenen** [comment]
Can you try if it works on https://demo.codimd.org/ and post a link here?

**Comment by kroschu** [comment]
https://demo.codimd.org/s/H1tB_rqWS

**Comment by SISheogorath** [comment]
This looks a bit like there is a something missing in the linuxServer.io image. @CHBMB can you have a look at this?

@kroschu can you provide the log output from the container when it switches from the editor view to 404?

**Comment by CHBMB** [comment]
I can only assume it's missing a dependency for Cryllic support.  I got no idea what though.... 
I agree some logs would be helpful

**Comment by CHBMB** [comment]
Also, just wondering, how is https://demo.codimd.org deployed?  Docker or some other method?

**Comment by SISheogorath** [comment]
@CHBMB the deployment of demo.codimd.org can be found here: https://community.codimd.org/t/how-do-you-use-codimd/18/2?u=sheogorath

**Comment by CHBMB** [comment]
@SISheogorath Think @thelamer has solved this one [here](https://github.com/linuxserver/docker-codimd/issues/6#issuecomment-511548799)
