### ISSUE TITLE
TED video embedding doesn't display on Firefox

### ISSUE THREAD

**Issue by offray** [codimd/server#135]
Hi,
I have just added a video embedding code from TED, like the following to a CodiMD document:

```html
<div style="max-width:854px"><div style="position:relative;height:0;padding-bottom:56.25%"><iframe src="https://embed.ted.com/talks/clay_shirky_how_the_internet_will_one_day_transform_government" width="854" height="480" style="position:absolute;left:0;top:0;width:100%;height:100%" frameborder="0" scrolling="no" allowfullscreen></iframe></div></div>
```
If I see this page from Chrome/Chromium, the code works properly, but it doesn't on Firefox 67.0.4. I don't know if this is only related with the browser of if there is something in the CodiMD side that makes it work properly on one browser but not in the other.

**Comment by SISheogorath** [comment]
I check and the iframes loads additional scripts which we stop by [CSP](https://content-security-policy.com/). It works in chrome because it has a fallback mechanism to a flash-based player and chrome has an embedded version of flash.

This is something we are most likely not going to change. I recommend to use a link to the video instead, sorry.

**Comment by offray** [comment]
Thanks... I'm now wondering if the only video sites working will be Vimeo and YouTube and if there is any way to extend CodiMD's macros syntax to have a Archive and Ted videos plugins on custom installations. There is any place to start to look for that source code?

**Comment by SISheogorath** [comment]
You can extent the CSP of your instance using the settings described for [`config.json`](https://github.com/codimd/server/blob/master/docs/configuration-config-file.md#csp-and-hsts) or [environment variables](https://github.com/codimd/server/blob/master/docs/configuration-env-vars.md#csp-and-hsts). This shouldn't require a modification of source code.

**Comment by offray** [comment]
Thanks a lot! I will see which one works better for us.
