### ISSUE TITLE
CSS Injection

### ISSUE THREAD

**Issue by kimbtech** [codimd/server#136]
By adding the following to the editor the whole gui will disappear and one won't be able to open the revisions.
Maybe css should be limited to the preview?
```html
<style>
  * { display:none; }
</style>
```

CodiMD Docker, Version 1.4.0

**Comment by SISheogorath** [comment]
We are open for implementations for a line of death. We consider the ability to use CSS in documents as a feature with all possible implications. 

But I'm open for suggestions to implement it in a way that prevents affects on other areas.
