### ISSUE TITLE
No TLS / STARTTLS with LDAP

### ISSUE THREAD

**Issue by Perflyst** [codimd/server#146]
Currently it is not possible to use a local LDAP server, e.g. `"url": "ldap://127.0.0.1"`

First of all the error does not tell you that there is an issue with the encrypted connection
```
Error: Could not determine UUID for LDAP user.
Check that either uidNumber, uid or sAMAccountName is set in your LDAP directory or use another unique attribute and configure it using the "useridField" option in ldap settings.
```

Please add a way to connect "PLAIN" or accept the ssl certificate even if it is for another hostname.
Current workaround:
`/etc/hosts`
`127.0.0.1 ldap.domain.tld`

**Comment by alecdwm** [comment]
Hey @Perflyst!
Has your custom TLS cert been signed by some root ca?
If so, you should be able to specify the path to the root ca certificate as detailed here:
https://www.npmjs.com/package/passport-ldapauth#active-directory-over-ssl-example

```javascript
{
  url: "ldaps://localhost",
  bindDN: "...",
  bindCredentials: "...",
  searchBase: "...",
  searchFilter: "...",
  searchAttributes: ["..."],
  tlsOptions: {
    ca: [
      fs.readFileSync("/path/to/root_ca_cert.crt")
    ]
  }
}
```

**Comment by Perflyst** [comment]
I would say this does not matter here? It is not signed for localhost nor the IP address so CodiMD crashes because of this?

**Comment by alecdwm** [comment]
Ah. If you want to disable the verification of TLS certificates entirely, you could try:

```javascript
{
  url: "ldaps://localhost",
  bindDN: "...",
  bindCredentials: "...",
  searchBase: "...",
  searchFilter: "...",
  searchAttributes: ["..."],
  tlsOptions: {
    rejectUnauthorized: false,
  }
}
```

**Comment by Perflyst** [comment]
Worked, thanks.
