### ISSUE TITLE
VIM Bindings

### ISSUE THREAD

**Issue by CrashLaker** [codimd/server#151]
Is it possible to have VIM Bindings when editing?

**Comment by ccoenen** [comment]
There should be a menu at the bottom of the editor that lets you choose vim, emacs or sublime.

![grafik](https://user-images.githubusercontent.com/124909/63524481-5f3ac300-c4fc-11e9-8466-6c4dc2d06fcf.png)

**Comment by ccoenen** [comment]
If this does not answer your question, or if you want to follow up on this one, feel free to post in here, and I'll reopen this issue.

**Comment by CrashLaker** [comment]
Awesome! Thank you!

**Comment by PhictionalOne** [comment]
I know this is closed, but what key is `normal mode` mapped to? You know good old vim `<ESC>`?
After looking into the referenced [vim.js](https://codemirror.net/keymap/vim.js) it should be `<C-[>, <C-c>` but either don't work for me. Neither on the instance I daily drive nor https://demo.codimd.org itself.
But maybe I am just stupid

**Comment by SISheogorath** [comment]
@PhictionalOne I guess this is a browser/OS related issue, could you open an own issue for that, where you might provide what browser and OS you use :)

**Comment by xeruf** [comment]
See also https://github.com/codemirror/CodeMirror/issues/5038
