### ISSUE TITLE
Embed link to imprint

### ISSUE THREAD

**Issue by morpheus-87** [codimd/server#157]
Is it possible to embed links to imprint and privacy?

**Comment by ccoenen** [comment]
We have a facility for the privacy statement:

`/server/public/docs` has a `privacy.md.example` file, you need to remove the `.example` ending and fill in the correct details for your instance.

This will then be linked to from the bottom of the landing page, like on our demo-instance: 
https://demo.codimd.org/s/privacy#
![grafik](https://user-images.githubusercontent.com/124909/63687131-0c1a8600-c804-11e9-8aaf-58747de61395.png)


I don't believe the same exists for imprint, yet.

**Comment by ccoenen** [comment]
With your permission I'd like to change the topic to "link to imprint" because this should be enhanced sometime in the future. And as far as I know that's not in place, yet.

**Comment by SISheogorath** [comment]
https://github.com/codimd/server/blob/master/docs/guides/providing-terms.md

It would be a good idea to also add an imprint link there. Thais is rather trivial, see https://github.com/codimd/server/commit/41a36e2e1877b4a2ab6751c011e80582f8ccbcf2

**Comment by morpheus-87** [comment]
I have opened a PR that adds a link to the imprint: https://github.com/codimd/server/pull/158

**Comment by SISheogorath** [comment]
Will be included in the next release. Would you go ahead and add this to the "providing terms" guide? Just noticed after merging that of course docs are missing :wink:

**Comment by morpheus-87** [comment]
Oh yes, I missed that. I added some instructions to the corresponding `README`: https://github.com/codimd/server/pull/165
