### ISSUE TITLE
My history notes on demo.codimd.org are totally lost

### ISSUE THREAD

**Issue by jdhao** [codimd/server#159]
I have taken a few notes on demo.codimd.org. Today when I login into the website with my GitHub account, I found that all my notes disappeared.

![image](https://user-images.githubusercontent.com/16662357/63820569-4d35a600-c97c-11e9-99ca-b8c649c2a882.png)

What happened? How do I get my notes back?

**Comment by SISheogorath** [comment]
Sorry to hear that! I just checked my own notes to verify we didn't rub into a bigger problem here, but it seems like everything is still in place.

I would like to invite you to join our community channel for a more interactive support conversation: https://riot.im/app/#/room/#codimd:matrix.org

Hope we can solve this ASAP.

**Comment by jdhao** [comment]
Thanks, I will register an account and start a discussion there.

**Comment by SISheogorath** [comment]
Please see your private messages on Riot :)
