### ISSUE TITLE
Incorrect Docker Secret Path

### ISSUE THREAD

**Issue by dargmuesli** [codimd/server#166]
Hey there,
could it be that this path is incorrect:
https://github.com/codimd/server/blob/6755d1b9897984d45001fd4aa1209854a5d69da6/lib/config/dockerSecret.js#L6
and should be `/run/secrets/` without `/var`? At least [according to the docs](https://docs.docker.com/compose/compose-file/#secrets) it should be, or am I completely mistaken?

**Comment by dargmuesli** [comment]
Oh well, `/var/run/` is symlinked to `/run/` as [explained on askubuntu.com](https://askubuntu.com/questions/57297/why-has-var-run-been-migrated-to-run). Is anything preventing a migration to the new path?

**Comment by SISheogorath** [comment]
No, feel free to change :) I really appreciate your investment into the community :heart:

**Comment by dargmuesli** [comment]
Thanks for your kind words :)
