### ISSUE TITLE
Add OpenAPIv3 documentation

### ISSUE THREAD

**Issue by ErikMichelson** [codimd/server#172]
It would be great to have an [OpenAPIv3](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md) conform documentation of the already existing REST endpoints like `/new`, `/{note}/info`, `/status` and so on.

**Comment by ccoenen** [comment]
I believe @SISheogorath has started working on this already?

**Comment by SISheogorath** [comment]
I started something, but never really finished the work on it. Would be nice when people would work on that. The original idea was to create a proper (versioned) REST API under the `/api/`, but maybe just documenting existing endpoints could already help.

**Comment by SISheogorath** [comment]
Thanks for your work @ErikMichelson!
