### ISSUE TITLE
My history notes on codimd server got wiped out again.

### ISSUE THREAD

**Issue by jdhao** [codimd/server#182]
Hi, my history notes on codimd server are lost again (previous issue [here](https://github.com/codimd/server/issues/159)).

This is what I performed before my notes got wiped out.  I tried to delete a note in the edit window and I confirmed the deletion. It seems that the note has been successfully deleted. But when I went to the history note page, the note was still shown. When I clicked the note to open it, I got a 404 error saying the note can not be found.

Then I tried to remove the note from history by clicking `x` on its top right. The tragedy happened: all notes were gone.

**Comment by SISheogorath** [comment]
There is in general something odd. When you delete a note yourself, it should also automatically get removed from your note history.

The "note is still in history after deletion"-bug should only appear when you someone else deleted a note you previously worked on.

Can you please provide some insight in what browser you are using?

**Comment by jdhao** [comment]
I am using the latest Google Chrome version on macOS.

**Comment by ccoenen** [comment]
I'm not sure how to proceed here. I can't reproduce this.

**Comment by ccoenen** [comment]
@SISheogorath maintains the demo instance, I hope he can help you.

**Comment by SISheogorath** [comment]
Ah sorry, I really have my head in other places the past few days:

> I'm not sure how to proceed here. I can't reproduce this.

I tried to reproduce when I asked here for the details and also couldn't reproduce on Firefox. Also did a rough check of the code and couldn't spot anything that speaks for the wiping.

@jdhao should I send you a list like last time?

**Comment by jdhao** [comment]
I believe it is caused by some hidden bugs since most of the time codimd works well. I have only met this issue recently.

@SISheogorath Can you just restore my history notes just before they are wiped out? If you provide a list, I have to click one by one the links to restore the note.

**Comment by SISheogorath** [comment]
@jdhao, that needs a lot more work (have to restore a db backup from before the disappearing, have to search for your user record, export the note history from there, inject it into the production instance, …)

I would recommend to:

1. Make a backup of your note history as soon as you restored it
2. Save your note history before deleting notes
3. Provide us with more details when you notice something

Right now, I can't see any reason why the note history should break .-.

PS: Check your Matrix account :)

**Comment by jdhao** [comment]
Hi @SISheogorath , I see the recovered note links. But when I click the links, I got 404 not found errors.

![image](https://user-images.githubusercontent.com/16662357/65853981-cb2b0980-e38d-11e9-990b-6cdd23d57fa8.png)

**Comment by SISheogorath** [comment]
I send you another link with everything restored. Hope that should fix all missing things

**Comment by jdhao** [comment]
Thanks, it works now.

**Comment by pierreozoux** [comment]
Actually we do also have this bug from time to time. Should we reopen it? or do you thin the version 2 has a different enough  backend that you are quiet confident it will not happen anymore?

I don't have more debug to give unfortunately..

**Comment by DerMolly** [comment]
As 2.0 is a complete rewrite I suspect, we will most likely don't transfer that bug, but only time will tell.

**Comment by Jesse-XIE** [comment]
same issue
