### ISSUE TITLE
Pad with Backup option (minimize risk of content deletion)

### ISSUE THREAD

**Issue by kolibril13** [codimd/server#195]
I want to create a pad for a collaboration idea.
The link wont be protected (mode "Freely"), so anyone can edit.
Now I am afraid that people could delete content by accident, or by bad intention.
Is there any option to make an automatic security backup every 24 hours ?
Or to revert major changes?
Or any kind of version control?
Or can there be an option that prohibits you to delete lines that you did not write yourself?
CodiMD is such a great tool for collaborating, so thanks for all your hard work!

**Comment by SISheogorath** [comment]
Hey, I have wonderful news for you: We record every version of the note automatically in the note revisions:

![image](https://user-images.githubusercontent.com/8719867/66590922-1913ee80-eb92-11e9-8e02-0e385b2a2482.png)

You can always go back to previous versions of this note in case someone does vandalism to it :)

I guess faster we can't solve this problem ;)

**Comment by kolibril13** [comment]
THIS IS AMAZING!
CodiMD is really close to perfection as a collaboration tool!

**Comment by ccoenen** [comment]
> THIS IS AMAZING!
> CodiMD is really close to perfection as a collaboration tool!

I will have this framed on my wall.
