### ISSUE TITLE
Add note revisions documentation

### ISSUE THREAD

**Issue by SISheogorath** [codimd/server#196]
After getting #195 and checking out features page, I had to notice, that we don't explain note revisions anywhere.

![note revisions](https://user-images.githubusercontent.com/8719867/66591137-8b84ce80-eb92-11e9-9473-38bd6624588e.png)

We should add some documentation about them to the [features.md](https://github.com/codimd/server/blob/master/public/docs/features.md).

**Comment by lucasrabiec** [comment]
I can take this one

**Comment by lucasrabiec** [comment]
Added: https://github.com/codimd/server/pull/198
