### ISSUE TITLE
Dev Server down

### ISSUE THREAD

**Issue by pomeara** [codimd/server#220]
Hi guys, I have noticed the dev server is down.  I have some notes I'd like to transfer if it's being decomissioned ;)

**Comment by SISheogorath** [comment]
Sorry, was just a reboot. Happens sometimes. I don't announce it, since it's a demo instance. We are usually back up within a few minutes. I think our longest downtime was 3 hours within the past 1 ½ years.

We wouldn't decommission it that without a long term notice.
