### ISSUE TITLE
Feature Request: Easy Change of font color

### ISSUE THREAD

**Issue by kolibril13** [codimd/server#228]
Let's say, I want to write something in green color.
I can do this like this:
```
</br> <span style="font-size:14pt;color:#7CFC00;">*Green text 1*
</span>
```
or like this
```
\``diff 
+ Green Text 2
\``
```
Note that the first \ should be also a ` , but I dont want github to render this part in this post.
This code  gives me:
![1](https://user-images.githubusercontent.com/44469195/69821471-0a49cf80-1204-11ea-9ad8-df4f4447ce58.png)
But it would be great to simpliy that to something like \green{text3}
What do you think?

**Comment by ccoenen** [comment]
We have the textmarker syntax `==some text==`
(example: https://demo.codimd.org/-9iUISbdTZ65UMW2Dv5kjQ)

Personally, I'm not a fan of adding random own syntax that is not part of any other Markdown spec.

**Comment by ErikMichelson** [comment]
You could use the textmarker syntax and a custom style tag like the following one for green highlighted text.
```html
<style>
    mark {
        background-color: #93F9C1;
        color: #168749;
    }
</style>

Some ==green== text
```

I edited the [previously linked example](https://demo.codimd.org/-9iUISbdTZ65UMW2Dv5kjQ) to match this.

**Comment by kolibril13** [comment]
Ohu, that is very nice! 
Thanks a lot.
