### ISSUE TITLE
Cannot get it to work with reverse proxy

### ISSUE THREAD

**Issue by finzzz** [codimd/server#231]
Somehow I cannot get this to work, I followed issue #162 but the server keep asking for example in homepage https://domain.com:3000/apple-touch-icon.png instead of https://domain.com/apple-touch-icon.png.

> version: '3'
> services:
>   database:
>     image: postgres:9.6-alpine
>     container_name: codimd-postgres
>     environment:
>       - POSTGRES_USER=hackmd
>       - POSTGRES_PASSWORD=hackmdpass
>       - POSTGRES_DB=hackmd
>     volumes:
>       - ./db:/var/lib/postgresql/data
>     networks:
>       backend:
>     restart: always
>   app:
>     image: quay.io/codimd/server:1.5.0-alpine
>     container_name: codimd
>     environment:
>       - CMD_DB_URL=postgres://hackmd:hackmdpass@database:5432/hackmd
>       - CMD_ALLOW_EMAIL_REGISTER=false
>       - CMD_DOMAIN=codimd.com
>       - CMD_PROTOCOL_USESSL=true
>       - CMD_URL_ADDPORT=true
>       - CMD_IMAGE_UPLOAD_TYPE=filesystem
>     ports:
>       - "3000:3000"
>     volumes:
>       - ./uploads:/codimd/public/uploads
>     networks:
>       backend:
>     restart: always
>     depends_on:
>       - database
> 
> networks:
>   backend:

haproxy config
>  ...
>         bind *:80
>         bind *:443 ssl crt /etc/haproxy/full.pem
> 
>         acl e_codimd_acl hdr(host) -i domain.com
>         use_backend codimd_backend if e_codimd_acl
> ...
> backend codimd_backend
>         server server1 192.168.10.10:3000 check

**Comment by SISheogorath** [comment]
You have to set `CMD_URL_ADDPORT=false` instead of `CMD_URL_ADDPORT=true`. I guess this should fix it :)

For further questions, feel free to reach out in the support chat: https://riot.im/app/#/room/#codimd:matrix.org

Or our Forum: https://community.codimd.org :)
