### ISSUE TITLE
typographer option

### ISSUE THREAD

**Issue by quite** [codimd/server#232]
The features page -- https://demo.codimd.org/features#Typographic-Replacements -- says:

    Enable typographer option to see result.

But it is not clear how to do this.

**Comment by ccoenen** [comment]
I think the documentation is not well written in that place. I don't know that any of these can be turned off or on, on the demo instance they "just work":

https://demo.codimd.org/o58dLhr_Qp2MfLCqzAbXnA

**Comment by quite** [comment]
You're right. I was a bit confused :)

**Comment by quite** [comment]
Didn't mean to close that. But where is the code is this replacement done?

**Comment by ccoenen** [comment]
this is part of [`markdown-it`](https://github.com/markdown-it/markdown-it), the library we use to render markdown.

It's in this file over there: https://github.com/markdown-it/markdown-it/blob/master/lib/rules_core/replacements.js

**Comment by quite** [comment]
I get a funky feeling from that code, or in general what it tries to accomplish. Like, trying to guess too much about periods. Do-what-I-mean is *hard*, so sometimes it's better to not try. But perhaps that all makes a bit more sense in some other language... Anyway, it's what we got presently :)

I'll adjust `features.md` slightly.

**Comment by ccoenen** [comment]
as a programmer, I'm not to keen on "quote replacement". I do have a visual design background as well, so I know why one would use actual quotes over the Inch symbol `"`, but in programming examples I usually _want_ inch symbols.

Anyways, if there's something specific you'd like changed, I'm afraid you'd have to take it up with the markdown-it maintainers. If it's alright with you, I'll close this issue.
