### ISSUE TITLE
 CMD_ALLOW_ANONYMOUS_EDITS is default false !

### ISSUE THREAD

**Issue by albjeremias** [codimd/server#247]
On the documentation  CMD_ALLOW_ANONYMOUS_EDITS says that the default is `true` when in reality is `false`.

Where it says:
>
> | `CMD_ALLOW_ANONYMOUS_EDITS` | `true` or `false` | If `allowAnonymous` is `true`: allow users to select `freely` permission, allowing guests to edit existing notes (default is `false`). |

>
> | `CMD_ALLOW_ANONYMOUS_EDITS` | `true` or `false` | If `allowAnonymous` is `true`: allow users to select `freely` permission, allowing guests to edit existing notes (default is `true`). This setting has no effect if CMD_EMAIL is false. The default for CMD_ALLOW_ANONYMOUS is true.|

https://github.com/codimd/server/blob/master/docs/configuration-env-vars.md#users-and-privileges

**Comment by Amolith** [comment]
I'll take a look at it this evening!

**Comment by SISheogorath** [comment]
Was fixed thanks to @Amolith with #259
