### ISSUE TITLE
Font paths broken if use CDN is false

### ISSUE THREAD

**Issue by bluehood** [codimd/server#253]
See reports [here](https://github.com/codimd/server/commit/23c7b5b0a6a4bb6ba79eb8ee61346de623f7aced#commitcomment-36762656): my PR to fix `urlPath` support, #242, broke the paths of certain fonts in some installations, e.g. in `build/cover-styles-pack.css`.

@MartB , @Techassi, how can one reproduce the problem? demo.codimd.org does not seem to be affected, although I remember @SISheogorath mentioning the he also saw some broken paths.

I can spend some time on this (seems right since I broke it and I'd rather have `urlPath` keep working rather than revert #242 :smile: ).

**Comment by MartB** [comment]
I have a fix you can test for subpaths, i will edit this comment with a repo link soon.

**Comment by bluehood** [comment]
Cool, thanks!

Is a standard manual setup enough to reproduce the problem?

**Comment by MartB** [comment]
It should be, i updated my long running installation from 313eb74 to 472ae01 and it broke.
The only thing that needs to be set is `useCdn false` i assume.

**Comment by bluehood** [comment]
To summarize what we have so far:

the issue can be reproduced with

```bash
$ cd server
$ bin/setup
$ # set .sequelizerc db to `sqlite://:memory:`
$ yarn run build
$ # set useCDN to false in config.json
$ npm start
$ firefox http://localhost:3000/
```

`"useCDN": false` is necessary to see the errors.

Console errors on homepage:

```js
downloadable font: download failed (font-family: "ForkAwesome" style:normal weight:400 stretch:100 src index:1): status=2147746065 source: http://localhost:3000/build/build/3a9e014c2469ffa65a0ea64a24e48b44.woff2
downloadable font: download failed (font-family: "ForkAwesome" style:normal weight:400 stretch:100 src index:2): status=2147746065 source: http://localhost:3000/build/build/44bbdbbfb5a10ba2d1ceba3c1e0fc1f5.woff
downloadable font: download failed (font-family: "ForkAwesome" style:normal weight:400 stretch:100 src index:3): status=2147746065 source: http://localhost:3000/build/build/fc46f3dae03b2b2e1ceed60971e90c9a.ttf
```

One (admittedly unsatisfactory) workaround is of course to set `useCDN` to `true`.
A possible fix is @MartB 's commit [here](https://github.com/MartB/server-1/commit/cc0c7cb34207152933cc7763b9215b041315d6e1). I'm not sure whether it's desirable to not use a webpack publicPath at all or whether it has other unintended consequences?

**Comment by Techassi** [comment]
> Is a standard manual setup enough to reproduce the problem?

Yes a standard and fresh installation ist enough to reproduce this problem.
Choosing `npm run build` or `yarn run build` doesn't result in a different result.

> One (admittedly unsatisfactory) workaround is of course to set useCDN to true.
> A possible fix is @MartB 's commit here. I'm not sure whether it's desirable to not use a webpack publicPath at all or whether it has other unintended consequences?

One even worse "fix" is to just edit the relevant CSS files. But this breaks even when running `build`.

**Comment by bluehood** [comment]
I don't understand how the URL for those files become `.../build/build`: why the double `build`? As far as I can tell `<base href="...">` is correct (it does not contain a `/build`) and the relative path in `public/buildcover-styles-pack.css` is also correct: `url(build/3a9e014c2469ffa65a0ea64a24e48b44.woff2)`, with just one `build`.

Where does the second `build` come from?

**Comment by Techassi** [comment]
I think the underlaying problem seems to be that `cover-styles-pack.css` is located in `build` and the imported font `[...]src:url(build/35e77a38ca9d85c4e8974261be764879.eot)` then tries to locate the font relative to itself which the results in `.../build/build`. 

Changing this to an absolute path / an relative one to `base` will fix this

**Comment by bluehood** [comment]
> the imported font then tries to locate the font relative to itself

Ah, yes, it's a relative URL and `cover-styles-pack.css` does not respect the html's `<base>` tag.
On the other hand, making the path absolute (via webPack configuration or otherwise), i.e. `/build`, will not work if CodiMD is served from a subpath.

As far as I understand, we should either enforce the `<base>` tag in `cover-styles-pack.css` & similar, or adjust the relative path, only for the css files that do not benefit from the `<base>` tag, by removing `build/`.

Does that make sense?

**Comment by Techassi** [comment]
> On the other hand, making the path absolute (via webPack configuration or otherwise), i.e. /build, will not work if CodiMD is served from a subpath.

Shouldn't the `base` tag then include the subpath as well? All content should get served via the subpath.

> by removing build/.

This seems like a good way to fix this... This would result in a relative path to `cover-styles-pack.css` and the font should be accessible through `.../build/35e77[...].eot`

**Comment by bluehood** [comment]
> Shouldn't the base tag then include the subpath as well?

Yes it will, but it won't matter if URL paths are absolute (which was the situation before my fix for urlPath, in which subpath installations did not work at all).

**Comment by Techassi** [comment]
Oh okay...

Removing `build/` from the CSS file seems the way to go then.

**Comment by bluehood** [comment]
So, proposed fix, if I can pull it off: change the webPack configuration so that the css files with the wrong `build/build` path have `publicPath` set to `./` instead of `build/`.

**Comment by SISheogorath** [comment]
Just wanted to let you guys know that the reason the Demo Instance is
unaffected is that it's not running the latest master. It broke on my
doing the redeploy so I did a rollback. Because I didn't have the time
to look into it completely (never deploy right before you want to go to
sleep ;))

I think we want support for relative URL as it was requested from time
to time and it seems to be the right thing to do. So I really hope you
can work this out, let me know if I can help (this weeks quite short on
time, but I'll do my best)

Anyway, looks like you have found the issue and now just need to find a
final solution for it. Maybe @davidmehren can give a hint about
webpack.

-- 
Signed
Sheogorath

OpenPGP: https://shivering-isles.com/openpgp/0xFCB98C2A3EC6F601.txt

**Comment by bluehood** [comment]
Yep if there's a webPack expert that can point me to the right lines/docs that would be greatly appreciated

**Comment by Techassi** [comment]
Maybe this issue from another project will help:

https://github.com/webpack-contrib/file-loader/issues/272

**Comment by bluehood** [comment]
@MartB @Techassi can you check whether [this commit](https://github.com/bluehood/codimd_server/commit/109c694669d25c9852d41aa4592f611ad1d0d004) solves the issue for you please? It solves my local repro.

**Comment by MartB** [comment]
Tested in #257

**Comment by Techassi** [comment]
#257 fixes this issue. Thank you!
