### ISSUE TITLE
Community site is down 

### ISSUE THREAD

**Issue by frode** [codimd/server#254]
https://community.codimd.org/

Response:

Oops

The software powering this discussion forum encountered an unexpected problem. We apologize for the inconvenience.

Detailed information about the error was logged, and an automatic notification generated. We'll take a look at it.

No further action is necessary. However, if the error condition persists, you can provide additional detail, including steps to reproduce the error, by posting a discussion topic in the site's feedback category.

**Comment by TheRojam** [comment]
I already reported it via the matrix-chat.

**Comment by SISheogorath** [comment]
I send the hosters an info, but I hope they enjoy their weekend and fix
it on Monday instead of today ;)


-- 
Signed
Sheogorath

OpenPGP: https://shivering-isles.com/openpgp/0xFCB98C2A3EC6F601.txt

**Comment by SISheogorath** [comment]
Got an email and it's up again :) Enjoy your stay ;)
