### ISSUE TITLE
Different path for uploaded images in export to pdf

### ISSUE THREAD

**Issue by lukaszniemkiewicz** [codimd/server#263]
Hi, 
while editing note this works for uploaded images but not for generated pdf:
`![](/uploads/upload_44431a5ad7ad469765adc3f401698fe2.png)`

this works for pdf but not for note preview:
`![](./public/uploads/upload_44431a5ad7ad469765adc3f401698fe2.png)`

**Comment by davidmehren** [comment]
As we had to disable PDF export for security reasons anyway, I'm going to close this issue. We might reimplement a server-side PDF export in the future. In the meantime, you can use your browsers print-to-PDF feature.
