### ISSUE TITLE
clicking "Edit this note" in the published note should default to the "Both" mode

### ISSUE THREAD

**Issue by stragu** [codimd/server#27]
When clicking the pencil icon ("Edit this note") in a published note page, the default mode should be "Both" (i.e. code on left, rendered on right) rather "View", the current default. That is, if the user has editing rights I guess.

Tested with "Freely" setting.

**Comment by ccoenen** [comment]
I think this would make a very nice first issue: The button leads to a URL that is essentially `/s/<note-id>/edit` which is then defined as a route here:

https://github.com/codimd/server/blob/f13a91c6988b55a0cd50fc530bdc13baa96bf3b4/lib/web/noteRouter.js#L18

and which will lead to this function that actually does the rediect.

https://github.com/codimd/server/blob/f13a91c6988b55a0cd50fc530bdc13baa96bf3b4/lib/response.js#L422-L437

So, essentially by changing this line, you could solve your own request:

https://github.com/codimd/server/blob/f13a91c6988b55a0cd50fc530bdc13baa96bf3b4/lib/response.js#L430

There's a similar thing in slides mode by the way, the two should be fixed at the same time:

https://github.com/codimd/server/blob/f13a91c6988b55a0cd50fc530bdc13baa96bf3b4/lib/response.js#L444

All that would be needed is to add `?both` to the url!

**Comment by stragu** [comment]
Thanks heaps for the explanations! I definitely some hand-holding :)

Hopefully this does it: https://github.com/codimd/server/pull/37

Cheers
