### ISSUE TITLE
logging in while editing note should redirect to note, not history

### ISSUE THREAD

**Issue by ccoenen** [codimd/server#272]
**Steps to reproduce:**

* be logged out.
* go to any note that requires being logged in to edit. For example https://demo.codimd.org/TCQO0GQ1QCiuag2TuMoTfg?edit
* type (which brings up the login modal
* log in

**Expected result:**

successful login should bring me back to that document

**Actual result:**

successful login lands me at https://demo.codimd.org - the history.

**Comment by SISheogorath** [comment]
If I'm not completely wrong this has the same causes as the issue below. Since the other issue is more active, lets move there :)

duplicate https://github.com/codimd/server/issues/273
