### ISSUE TITLE
Localization issue: moment.js locale is not set

### ISSUE THREAD

**Issue by numero-six** [codimd/server#275]
When `format` is called on moment, the locale is always the default (`en`). It break the UI localization when, for instance, there is a call like:

```js
moment(time).format('llll')
```

It just seems the `moment` is not confiured: calling

```js
moment.locale('fr');
```

to set the locale seems to fix that.

**Comment by ccoenen** [comment]
Would you say this is a setting per user, or per server or should we just default to the selected language ... (or or or :-) )

**Comment by numero-six** [comment]
@ccoenen i don't know but it must be consistent with the locale used when calling `__`.

```
<%= __('Export') %>
```

Most of the time, `format` is called with some translated string around, ie `'Started at ' + moment().format('llll');`, so locale used to translate 'Started at' should be the same.

**Comment by numero-six** [comment]
I don't understand why the issue is marked as `enhancement`, it's clearly a `bug` one. The interface is broken, the user can be exposed to an UI being half localized, half not-localized.

It's not a minor issue: as you may know, a date formatted as "04/02/2020" may be interpreted as February 4th, or April 2nd whereas the reader is english or not. That could lead to serious misunderstandings for non-english speaking people and a negative UX.

> Would you say this is a setting per user, or per server or should we just default to the selected language...

I don't know what is the good choice but that's not the issue here. The locale can be chosen guessed/per user/per instance/whatever. In every case, we should never be confronted to a UI with some buttons translated and some not: the locale chosen should be applied everywhere.

**Comment by ccoenen** [comment]
Well, we're all just humans doing this in our spare time. If it makes you happy I'll add "bug" instead.

**Comment by ErikMichelson** [comment]
In the [frontend for version 2.0](https://github.com/codimd/react-client) this issue is fixed already. For the next patch version of 1.x I wrote a quick fix.
