### ISSUE TITLE
Necessary OIDC scopes for email & profile retrieval are missing

### ISSUE THREAD

**Issue by elespike** [codimd/server#276]
The OAuth2 request to the configured authorization endpoint lacks any `scope` parameter and will generally fail to retrieve user profile information.

See [https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims](https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims) for additional details.

Proposed changes:
[https://github.com/elespike/server/commit/85be54bb0a385f9297ddef34d1006081c7ee334f](https://github.com/elespike/server/commit/85be54bb0a385f9297ddef34d1006081c7ee334f)

**Comment by SuperSandro2000** [comment]
Could you create a PR with this change?
Are you aware of any breaking changes this could cause with existing oAuth2 login setups?
Also if you do so can you please update the doc [here](https://github.com/codimd/server/blob/master/docs/configuration-config-file.md#oauth2-login)?

**Comment by elespike** [comment]
I'm not aware of any breaking changes. In fact, I'm surprised this has worked with other OAuth2/OIDC providers. Perhaps Mattermost/NextCloud aren't fully complying with the OIDC standard.

What updates did you mean for the doc? Just add `scope` to the list of example values?

**Comment by SuperSandro2000** [comment]
That could be the case.

Yes, please. If you find any other places it would need an update/mention please also update them. :)

**Comment by DerMolly** [comment]
this issue seems to be fixed with the merging of the linked PR...
So this can be closed, right?
