### ISSUE TITLE
Can't choose theme in slideOptions

### ISSUE THREAD

**Issue by micedre** [codimd/server#279]
When adding a theme in `slideOptions` in YAML metadata, it doesn't appear in the generated slides. 
It comes from the way codimd detects if a theme exists or not in [lib/web/note/util.js](https://github.com/codimd/server/blob/master/lib/web/note/util.js#L104), the filesystem path used is not the right one.

**Comment by SISheogorath** [comment]
This should be fixed in master as well as 2.0
