### ISSUE TITLE
Rework database models to TypeScript definitions

### ISSUE THREAD

**Issue by SISheogorath** [codimd/server#281]
With 2.0 we'll switch to TypeScript as base language. Therefore we should work on rewriting all database models to proper TypeScript. A few first steps are already done, but it would be great to follow the [TypeScript best practices from Sequelize](https://sequelize.org/v5/manual/typescript.html).

The branch to do these changes to is `release/2.0.x` and all files can be found here:
https://github.com/codimd/server/tree/release/2.0.x/lib/models

**Comment by davidmehren** [comment]
Fixed with #338 :partying_face:
