### ISSUE TITLE
Setup eslint for TypeScript

### ISSUE THREAD

**Issue by SISheogorath** [codimd/server#282]
Currently out eslint definitions are setup for regular JavaScript. It would be great to get a mixed mode running until the rewrite to TypeScript is completed. Since I'm not an eslint expert and my first attempts ended up with two separate config files which also threw a bunch of errors and warnings, I would love to see someone taking care of this and adding some static code analysis to TypeScript.

If that means we will have to use 2 different config files, it's fine, but of course having just one config file is preferred.

If you get something working, please file the PR against the `release/2.0.x` branch :)

**Comment by ErikMichelson** [comment]
See 0228d00
