### ISSUE TITLE
published article shows blank page

### ISSUE THREAD

**Issue by zhangyoufu** [codimd/server#287]
The web page cannot render due to `<script src="config"></script>`. This is a bug introduced by https://github.com/codimd/server/commit/23c7b5b0a6a4bb6ba79eb8ee61346de623f7aced#diff-34499b5f14a9453387dbc259cc08c401 (missing `/` before `config`) and affect release 1.6.0

**Comment by zhangyoufu** [comment]
and `<link href="build/font-pack.css" rel="stylesheet"><link href="build/pretty-styles-pack.css" rel="stylesheet"><link href="build/pretty-styles.css" rel="stylesheet"><link href="build/pretty.css" rel="stylesheet">`

**Comment by SISheogorath** [comment]
Please set up your codimd server properly. It seems like you are lacking a proper configuration for the `domain` setting. This can to various problems including the ones you described. We use the `<base>` statement now, which provides a proper navigation for relative URLs. But of course it's only working when set to a useful value, which is not the case when CodiMD isn't configured.

We aim to improve this for 2.0 by making a proper configuration mandatory, but so far, we only warn you on startup about the settings you should set.

**Comment by zhangyoufu** [comment]
It seems that `<base>` element conflicts with our CSP configuration (`add-header` in nginx), and Chrome reports an error `Refused to set the document's base URI to 'https://example.com/' because it violates the following Content Security Policy directive: "base-uri 'none'"`.
