### ISSUE TITLE
Allow option to tunnel uploads from s3/minio through the server

### ISSUE THREAD

**Issue by martin31821** [codimd/server#304]
I don't like the idea of exposing my uploads world-readable provided the note-id and filenames are known, I'd like to see either the usage of S3 presigned links or allow an option to tunnel the upload through the server itself.

What do you think about this?

**Comment by SISheogorath** [comment]
Ehm… We already tunnel uploads through the server. :sweat_smile: And for images in general, we want to go for #95 in future with version 2.0. I hope this lands on initial 2.0 release, but no promises.

**Comment by martin31821** [comment]
#95 seems to be what I'm looking for. 

I meant the download path of the images, where my local 1.6 image hands out s3 urls.
