### ISSUE TITLE
Umlauts and ß replaced by ? in export file name

### ISSUE THREAD

**Issue by davidak** [codimd/server#307]
Server version: 8ce7b285636c02b4215c838640bb748947c8317f

![Screenshot from 2020-03-22 20-54-28](https://user-images.githubusercontent.com/91113/77259100-78b51080-6c7f-11ea-8c4a-08c2b9a159a0.png)

**Comment by davidmehren** [comment]
I just tried with 1.6.0 and in both the downloaded .md file and the exported zip the characters had the correct encoding and are not `?`. I'm currently running on Linux, Node 14 and used Firefox 79.0b5 to download. Could you detail your setup a bit so we can try to find the culprit?

**Comment by davidmehren** [comment]
Can't reproduce & and no response, closing.
