### ISSUE TITLE
Presentation: PDF-Export invisible content

### ISSUE THREAD

**Issue by margau** [codimd/server#308]
Hi,
the content is invisible when trying to export an presentation to PDF.
URL: /p/{pad-name}?print-pdf#/
Version: git tag: 1.6.0
Browser: Latest Chrome under Ubuntu Linux and Windows

The text is embedded to the PDF, but invisible when using chrome's "save to pdf". Background graphics is enabled. Using the same browser on a raw reveal.js-presentation, everything works fine - therefore probably not an issue with reveal itself.
https://demo.codimd.org/p/slide-example?print-pdf#/ is also affected.

Please let me know if you need any further information!
margau

**Comment by margau** [comment]
An Update: Seems that div "background" is layed over div slides, making the slides invisible. I have no idea why this happens in codimd, but not in plain reveal.

**Comment by SISheogorath** [comment]
Thanks for looking into that.

For a deeper look these files might be useful:

https://github.com/codimd/server/blob/1.6.0/public/css/slide.css
https://github.com/codimd/server/blob/1.6.0/public/views/slide.ejs

**Comment by margau** [comment]
Some brute-forcing in chrome devtools showed, that removing 
```css
.reveal .slides, .reveal .backgrounds, .reveal.overview {
    transform-style: preserve-3d;
}
```
(Line 258-260)
in https://github.com/codimd/server/blob/1.6.0/public/css/slide.css fixed the issue. What does this block do?
