### ISSUE TITLE
Collaborate on external files

### ISSUE THREAD

**Issue by TianPuJun** [codimd/server#310]
Collaborate on external files
I want to enter a file URL to collaborate in codimd

**Comment by SISheogorath** [comment]
Could you please describe your feature request a bit more elaborated? If you are unable to do this in English, please refer to your main language and hopefully someone in the community or Deepl/Google can translate. Looking forward to read from you :)

**Comment by TianPuJun** [comment]
The current collaborative editing should be on the internal files of codimd, but I want to perform collaborative editing on the external markdown files. For example, I know the URL of a test.md file, and load it by specifying the URL of test.md when codimd loads the file content

**Comment by TianPuJun** [comment]
1. 我想使用codimd作为插件式的安装到vue项目中，并且可以使用自己本系统的文件来达到在codimd中协作编辑的目标。
2. 如果我想使用这个在线协作的功能，除了模拟登录codimd系统之外还有其它的方式吗？
您好我大概的想法就是如此，不知您能理解我的描述吗，谢谢
