### ISSUE TITLE
Add option for socket permissions

### ISSUE THREAD

**Issue by petabyteboy** [codimd/server#317]
When using the config.path option, it would be nice to have an additional option to set the group and permissions of the socket after it has been created to allow the reverse proxy to access it.

By default it looks like this:

```
[mil@pad:~]$ ls -l /run/codimd/
total 0
srwxr-xr-x 1 codimd codimd 0 Apr  2 16:13 codimd.sock
```

So the reverse proxy would not be able to access it.

**Comment by dalcde** [comment]
This is now fixed in release/2.0.x
