### ISSUE TITLE
Presentation Mode backgrounds not working

### ISSUE THREAD

**Issue by zeigerpuppy** [codimd/server#320]
I have upgraded my install (docker) from an old server, I am building the docker container from the `master` Debian branch.
The transition went well apart from one small issue:

In presentation mode, I have previously used custom slide backgrounds with the syntax:

```markdown
---
<!-- .slide: data-background="/uploads/upload_58bf6df16014d8b756b5e288471fc8dc.jpg" -->

# Slide name

- slide content

---

```

This syntax no longer seems to show the slide background in the presentation.  
The other forms of slide background still work (including `.slide data-background-iframe`).

Is anyone aware of a change in the syntax?

I have looked for errors in the html error and the docker machine, but no error messages are coming up.

**Comment by davidmehren** [comment]
I just tried to reproduce this issue but that syntax worked for me: the background image was shown correctly.

Could you try to reproduce the problem on demo.codimd.org?

**Comment by zeigerpuppy** [comment]
@davidmehren , apologies, my error, I had a syntax problem in the document header, working properly now.
Can close this issue.
