### ISSUE TITLE
Support WebRTC

### ISSUE THREAD

**Issue by voidspacexyz** [codimd/server#326]
Can we introduce a WebRTC support with audio only or screenshare calls, this would enable codimd as a complete collaborative solution.

**Comment by fbartels** [comment]
WebRTC calls can be a complex matter so maybe it would be wiser to integrate an existing solution. If there is interest at my place of work we are building a video meeting software which could be integrated with a post message API. Let me know if you would be interested.

(I left the name out to not leave the impression of just wanting to advertise)

**Comment by ccoenen** [comment]
I think the better way to go about it would be to integrate CodiMD with JitsiMeet (for example). Both would remain separate projects, of course.

**Comment by InnayTool** [comment]
A complete collaborative solution is currently not a project goal. There are many software projects which can be used for voice chat and in some cases implement solutions for collaborative editing or make it possible to integrate an external tool like codimd.
