### ISSUE TITLE
Ldap Authentication StartTLS Support

### ISSUE THREAD

**Issue by Skgland** [codimd/server#329]
We would like to use StartTLS for our ldap authentication, but 
the starttls flag is not passed on to passport-ldapauth.
Which should support this as of [this commit](https://github.com/vesse/node-ldapauth-fork/pull/70).

As far as I can tell these two files would probably be the relevant ones for this issue:

https://github.com/codimd/server/blob/49e8be44e1028da718b26b6ab0dcf7e0b3e00b94/lib/web/auth/ldap/index.js#L15-L23

https://github.com/codimd/server/blob/49e8be44e1028da718b26b6ab0dcf7e0b3e00b94/lib/config/default.js#L130-L141

**Comment by davidmehren** [comment]
Closing, as the PR was merged into the 2.0 branch.
