### ISSUE TITLE
MathJax elements in lists are rerendered on change

### ISSUE THREAD

**Issue by n0emis** [codimd/server#331]
I have a mathjax element in a list like here:
```markdown
* This is a formular $f(x)=x^3$  is the same as $f'(x) = 3x^2$
* Prove:
$$
  {f(x+h)-f(x) \over h} = {(x+h)^3-x^3 \over h} \\  
  = {x^3 + 3x^2h + 3xh^2 + h^3 - x^3 \over h} = ... = 3x^2 +3xh + h^2
$$
* This is a Text
```
When I now change something in ANY part of the list, this causes everything to be rerendered. During this process, the size of the mathjax output "jumps" around, leading to e.g. messing up the scrolling etc..

This is how it looks like:
![output](https://user-images.githubusercontent.com/22817873/79991262-5f87c580-84b2-11ea-9bb7-dd77831d775b.gif)

Is it possible to maybe cache the result to prevent this?

**Comment by ErikMichelson** [comment]
Sounds similar to #197

**Comment by n0emis** [comment]
Yes, thanks. I'll close this in favour of #197 ...
