### ISSUE TITLE
I cant input images

### ISSUE THREAD

**Issue by TimeS0ng** [codimd/server#336]
when I try to input a jpg, there is no response , and the image always can not input.
I used the docker to install the codimd.

![image](https://user-images.githubusercontent.com/26432578/80268367-ffbf3380-86d8-11ea-9a23-90e38be57384.png)

**Comment by SISheogorath** [comment]
Do you see any error message in the container log using `docker-compose logs app`?

Also, which version are you running? The link at the bottom of the index page should link to the exact commit.

This should help us to help you 🙂

**Comment by DerMolly** [comment]
@TimeS0ng Any update on that? If not I'd like to close this issue as we have no indication what the problem could be...

**Comment by Darkyere** [comment]
I am having the same issue.

I am using HedgeDoc in docker on Ubuntu 20.04.

When i try to upload and image it just stays at uploading.

The image however does end up in uploads folder.

----

```
The HedgeDoc container logs looks as following


2021-02-12T09:44:52.310Z info: 	deserializeUser: 0ff6f19f-e643-449d-acb0-7458317af741


(node:306) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: /uploads/


    at onParseError (internal/url.js:257:9)


    at new URL (internal/url.js:333:5)


    at new URL (internal/url.js:330:22)


    at Object.exports.uploadImage (/opt/hedgedoc/lib/web/imageRouter/filesystem.js:28:19)


    at /opt/hedgedoc/lib/web/imageRouter/index.js:63:22


(node:306) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
```

----

Any help would be appreciated since me and a freind is considering using this to share notes and documents.

Best Regards,
Darkyere

**Comment by SISheogorath** [comment]
@Darkyere please see the related forum post:

https://community.hedgedoc.org/t/filesystem-uploads-in-codimd-container/94
