### ISSUE TITLE
Labelled links in pdf export

### ISSUE THREAD

**Issue by SimonRassmann** [codimd/server#340]
For labelled links, both the label and the path appear in the pdf export.

Example:
`[Link](github.com/codimd)`
should produce a clickable link labelled Link and nothing else in the pdf, yet the result is
![labelled_link_pdf](https://user-images.githubusercontent.com/54679484/80308117-586ff880-87cd-11ea-9894-07a9c069f70c.png)

**Comment by SISheogorath** [comment]
The reason we use this postfix written version is that people sometimes actually print documents. And having an underlined link in there, doesn't really help. Therefore we add the link intentionally in the print-view.
