### ISSUE TITLE
new notes created via freeurl-mode are created with content 'null'

### ISSUE THREAD

**Issue by DerMolly** [codimd/server#343]
When you create a note via freeurl-mode the note gets created with the default content of 'null'

**Comment by ccoenen** [comment]
I can confirm this behaviour.

**Comment by ErikMichelson** [comment]
The bug is fixed in the 2.x branch. Maybe we should create a backport for current master for a bug-fix release after 1.6?

**Comment by SuperSandro2000** [comment]
Done in #347

Also this issue didn't get closes with the first PR. I wonder why.

**Comment by SISheogorath** [comment]
> Also this issue didn't get closes with the first PR. I wonder why.

Because issues only get closed, when the content of a PR hits the default branch.
