### ISSUE TITLE
default values for environment variables

### ISSUE THREAD

**Issue by oupala** [codimd/server#348]
The documentation is listing [environment variables](/codimd/server/blob/master/docs/configuration-env-vars.md) but does not provide the default value of each variable.

The default value, and a **required** flag should be specified for each variable.

**Comment by oupala** [comment]
As my previous pull request #404 has been merged, are you interested in adding the default value for each variable?

**Comment by oupala** [comment]
@ccoenen

**Comment by ccoenen** [comment]
I'm currently not able to put in any meaningful amount of time. I'm really sorry, but this won't change any time soon.

**Comment by oupala** [comment]
I was just asking for an opinion.

I offered to do it myself.

**Comment by SISheogorath** [comment]
I don't think we should add another row to the tables. It's already super dense.

Also there is currently only the database config we require. Everything else can be left on default and CodiMD would work. It's recommended to set some more things, like `CMD_DOMAIN`, but technically it works without.

**Comment by oupala** [comment]
@SISheogorath Your point is about a **required** column.

What about a **default value** column?

**Comment by SISheogorath** [comment]
I don't think a defaults value row would make the tables less crammed. Looking at the GitHub rendering I already think that readability is questionable and would only decrease even further.

Therefore I advise against more column of any kind.

**Comment by oupala** [comment]
My opinion is that readability worth nothing if mandatory information are not there.

Most of the configuration parameters are optional. But to guess if you want to override them or not, you have to know their default value, otherwise it is useless to offer default value without mentioning them in the documentation.

And if people have to look at the doc, it means that the documentation is missing some important informations. You can be a user of codimd, an admin of codimd and not being able to look at js code and understand it.

**Comment by SISheogorath** [comment]
I'm not saying we shouldn't provide this data, but maybe such a table is simply the wrong representation. Maybe we should create a short overview table for config option instead? 

Or be creative in another way. I'm open for ideas here, I just don't see how another column would actually improve the documentation.

**Comment by oupala** [comment]
Trying to be creative, I tought that we could add the default value as the first example on each `example` cell.

**Comment by davidmehren** [comment]
I think we could even replace the "example value" column with a "default value"  column. The possible options could be mentioned in the description.

**Comment by oupala** [comment]
I think that removing example values would not serve the users. I then decided to change the name of the *example* column to change its name from `example value` to `**default** and example value`.

It allows to get the default value in bold, and then one or multiple other example values. This solution does not add another column.

Please find this proposal in the following pull request #464.
