### ISSUE TITLE
Integration with discourse

### ISSUE THREAD

**Issue by tttp** [codimd/server#353]
Hi,

We are trying to find a way to mix better async and synchronous communications in our lockdown time.

So far, we are mixing discourse for things that don't need realtime communication, but we have video calls from time to time and are using google doc to take notes.

I was wondering if it'd be possible to integrate codimd with discourse for note taking+history:
- before the meeting, we have the agenda as a topic
- when the meeting starts, the host clicks on the magic codimd button, create a new note and everyone can add live edit the document and take notes
- when the meeting is over, the host clicks on another magic button and the codimd note is added as as the minutes as a new reply under the initial agenda topic

I've read that the API is a work in progress, but would it already be possible with minimal development?

**Comment by davidmehren** [comment]
This sounds to me like you are searching for a script or tool that 'glues together' Discourse and CodiMD using their APIs. As you might understand, such a tool is a bit out of scope for this repository. Therefore I'm going to close this issue. I recommend using the [community forum](https://community.codimd.org) (coincidentally also a Discourse) to ask for help there. If an actionable request develops (like "the API should be able to do X"), feel free to open another issue.
