### ISSUE TITLE
Replace or remove connect-flash

### ISSUE THREAD

**Issue by davidmehren** [codimd/server#357]
We are currently using [connect-flash](https://github.com/jaredhanson/connect-flash) to e.g. display "login successful" to the user. This library has not been updated since 7 years and uses deprecated APIs (`Util.isArray` is deprecated since Node 4). We might want to replace it or update the code and move it into our repo.

**Comment by SISheogorath** [comment]
Definitely a good idea. Each dependency we can get rid off, doesn't influence our release cycles, which is much appreciated.

**Comment by DerMolly** [comment]
As we don't use connect-flash in the new frontend I think this issue can be closed.
