### ISSUE TITLE
Stop UI from jumping by placing cover-container at top instead of middle

### ISSUE THREAD

**Issue by eipiminus1** [codimd/server#359]
I suggest to place the `cover-container` with search bar and the cards always on the top. This makes it easier to access the search fields and buttons while the cards are still loading.

**Use case**

I use CodiMD frequently for all my notes. I have a shortcut for it in my taskbar and keyboard shortcuts to quickly access it. I usually want to either create a new note or search for an existing one. Creating a new one is fast and seamless. I can reach the blue button on the top right or go to /new directly.
For search I have to wait until the pads are loaded and the view is updated. Then I can place the cursor in the search box and start typing. If I try to go for the search bar while the cards with my pads aren't loaded I usually click at one of them instead of the search bar because the appear just before I hit the search bar. Placing it on the top, no matter how many cards are displayed would top the UI from jumping around.

Additionally placing the cursor in the search bar by default would be awesome :)

**Comment by eipiminus1** [comment]
Taking a quick look it seems that the behavior could be achieved by changing this line to `vertical-align: top;`

https://github.com/codimd/server/blob/4fc7f0c5a2cc548e079642e9f47e5f7573921ff0/public/css/cover.css#L53

**Comment by DerMolly** [comment]
This should be solved with the upcoming 2.0.

**Comment by eipiminus1** [comment]
Thank you for the quick response.

I'm looking forward to the 2.0 release then. I patched it in my current installation so I don't mind waiting for 2.0 for the fix.
Just for the record: I also had to update line 165
https://github.com/codimd/server/blob/4fc7f0c5a2cc548e079642e9f47e5f7573921ff0/public/css/cover.css#L165
