### ISSUE TITLE
SAML request format support

### ISSUE THREAD

**Issue by chenboshiun0109** [codimd/server#362]
Hello CodiMD Support:

We config SAML on CodiMD and used Azure AD as  identity provider, but some of user can't login CodiMD via SAML, due to Authentication method doesn't match, see detailed error as the following:

Authentication method 'MultiFactor' by which the user authenticated with the service doesn't match requested authentication method 'Password, ProtectedTransport'

We issue support request to Azure Support, he noticed not support MultiFactor in CodiMD's SAML request format, need to update CodiMD's SAML request format.

Currently, Azure Support suggest two update method:

1. remove SAML AuthnContext on SAML request format

2. specify "unspecified"  on AuthnContextClassRef 

But we don't know above method to see if it is ok or not. 

So We need you help me check this issue.  

I invited Azure Supoort join this issue request,  maybe we can share related infomation each other

If you have any question, please let me know,

**Comment by MikeRen0** [comment]
Hello CodiMD Support:

As some of the SSO scenarios no longer rely on password, it is more recommended to unspecify or remove AuthnContextClassRef in SAML request to avoid sign-in trouble for users who are using modern authentication methods like Passwordless sign-in and Windows Hello for Business. 

Kindly refer to the following two ways and advise if you can help to apply the change at the app server side. Thank you.
 
1.	Unspecify AuthnContextClassRef.
 <samlp:RequestedAuthnContext xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" Comparison="exact">
<saml:AuthnContextClassRef xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">urn:oasis:names:tc:SAML:2.0:ac:classes:Unspecified</saml:AuthnContextClassRef>
 
2.	Remove AuthnContextClassRef.
According to th OASIS’ SAML specification document, AuthnContextClassRef is optional in SAML request. 
https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf
 
2.7.2.2 Element The element specifies the context of an authentication event. 
The AuthnContext element can contain an authentication context class reference, an authentication context declaration or declaration reference, or both. Its complex AuthnContextType has the following elements: 
 
AuthnContextClassRef [Optional] 
A URI reference identifying an authentication context class that describes the authentication context declaration that follows.
 
AuthnContextDecl or AuthnContextDeclRef [Optional] Either an authentication context declaration provided by value, or a URI reference that identifies such a declaration. The URI reference MAY directly resolve into an XML document containing the referenced declaration.

**Comment by SISheogorath** [comment]
I just looked into the code for this and it might not even be a bug. We have a config option to disable the AuthContext: 

```
CMD_SAML_DISABLEREQUESTEDAUTHNCONTEXT=true
```

or if you use the `config.json` this should work (if added in the production config section):

```json
saml: {
  "disableRequestedAuthnContext": true
}
   
```

Some documentation on the option:
https://github.com/codimd/server/blob/master/docs/configuration-env-vars.md#saml-login (ours)
http://www.passportjs.org/packages/passport-saml/ (upstream module docs)

If this doesn't solve your problem, feel free to let me know :)

Code:
https://github.com/codimd/server/blob/d30e022c7f4c0b05e4f4424a35c771678baa477b/lib/web/auth/saml/index.js#L15-L22
