### ISSUE TITLE
override the configuration file path

### ISSUE THREAD

**Issue by oupala** [codimd/server#364]
As [documented in the documentation](https://github.com/codimd/server/blob/master/docs/configuration-env-vars.md#codimd-basics), it should be possible to override the configuration file path using a `CMD_CONFIG_FILE` variable.

However, the environment variable is [not parsed in environment.js](https://github.com/codimd/server/blob/d30e022c7f4c0b05e4f4424a35c771678baa477b/lib/config/environment.js). The variable seems to be parsed in [index.js](https://github.com/codimd/server/blob/d30e022c7f4c0b05e4f4424a35c771678baa477b/lib/config/index.js):

https://github.com/codimd/server/blob/d30e022c7f4c0b05e4f4424a35c771678baa477b/lib/config/index.js#L33-L34

I'm storing the configuration file to `/config/config.json` and I set `CMD_CONFIG_FILE = /config/config.json`. Should it work like that?

I'm not sure about the value of appRootPath as I am in a container where codimd in installed in `/codimd`:

https://github.com/codimd/server/blob/d30e022c7f4c0b05e4f4424a35c771678baa477b/lib/config/index.js#L13

**Comment by SISheogorath** [comment]
Yes, this should work. The `path.resolve` function can handle relative and absolute paths. Relative paths are relative to the first argument, (means approot) but when you provide and absolute path, this will be used.

For this kind of support requests, I would recommend to use [the Forum](https://community.codimd.org/) as it's more accessible than GitHub issues.

Hope that answers your question :)

**Comment by oupala** [comment]
Unfortunately, that does not work in my situation...

I did not knew about the forum. I'll have a look at it.

**Comment by oupala** [comment]
In fact, I'm having a very strange behavior:

- my configuration file `/config/config.json` seems to be used
- the configuration file of codimd `/codimd/config.json` seems to be used also

I can guess that my configuration file is used because I've set a loglevel to an invalid value:

```json
"loglevel": "debug-test",
```

And I get a consistent error in the logs: 

> 020-05-20T12:19:18.163Z error: 	Selected loglevel debug-test doesn't exist, using default level 'debug'. Available options: debug, verbose, info, warn, error

But I think that is using the codim config file as I also get this error:

> 2020/05/20 12:18:43 Waiting for: tcp://hackmdPostgres:5432
> 2020/05/20 12:18:43 Problem with dial: dial tcp: lookup hackmdPostgres on 10.16.100.160:53: no such host. Sleeping 1s

And this database configuration comes from the configuration of the [codimd container repo](https://github.com/codimd/container/blob/9bfa01b21fabcea0e9fb164b4abb86f7921ede0b/resources/config.json#L5-L12).

I don't understand how codimd manages to get configuration from two different files at the same time...

Just to be clear, my own `/config/config.json` also has a database configuration to use sqlite:

```json
        "loglevel": "debug2",
        "db": {
            "dialect": "sqlite",
            "storage": ":memory:"
        },
```

But my own sqlite database configuration seems to be overriden by the one from the codimd container postgres database configuration.

**Comment by SISheogorath** [comment]
This is because the container image we develop is not intended to be used with a config file in general. It provides a default database config via environment variables (which is required to make the waiting for the DB work). I highly recommend to use environment variables instead and only use a config file for settings your can't change by environment variable.

**Comment by oupala** [comment]
I was intending to do that, but then I tought about that and I wanted to use a real MariaDB database for the production instance, where I would pass database credentials using the environment variables. I also want to use a small sqlite database provided by the test profile of the `config.json` file for dev and test instances. This would be great to support such configurations.

As far as I understand the `CMD_CONFIG_FILE` environment variable has no effect when using the codimd container image?

**Comment by SISheogorath** [comment]
It works as intended, except of the database configuration. In the container the database configuration is required to be supplied as environment variable due to the way, we build the entrypoint script:

https://github.com/codimd/container/blob/9bfa01b21fabcea0e9fb164b4abb86f7921ede0b/resources/docker-entrypoint.sh#L21-L31

You can either provide a `CMD_DB_URL` besides your `config.json` or you have to change the way the container works. (For example only with a config json your database migrations won't run either.)

**Comment by oupala** [comment]
Ok, I had a look at the docker-entrypoint.sh file. I've seen that there is a default database configuration hard-coded in this file.

I then tried to configure an sqlite database but I'm not sure of the syntax I used as the documentation is not very clear on this point.

I used `sqlite::memory:` and I'm not sure it is working as I can see some problem in the log:

```log
2020/05/29 14:56:06 Waiting for: tcp://sqlite::memory:
2020/05/29 14:56:06 Problem with dial: dial tcp: address sqlite::memory:: too many colons in address. Sleeping 1s
2020/05/29 14:56:07 Problem with dial: dial tcp: address sqlite::memory:: too many colons in address. Sleeping 1s
```

**Comment by SISheogorath** [comment]
The container setup doesn't support non-external databases. The database has to have a hostname or IP address as the entry point script will wait for it to be available before going any further. It does neither support sqlite, nor any other non-tcp socket connection based database.

**Comment by oupala** [comment]
I find it quite hard to understand how codimd can be configured.

It can be configured by a config file, it can also be configured using environment variable, but some parameters are in common on both sides, but not all. Some parameters are not documented at all (example : `linkifyHeaderStyle`), and some deployment styles (such as container) are hard-coding some values, overriding the configuration.

I would propose to merge `docs/configuration-config-file.md` and `docs/configuration-env-vars.md` in a single `configuration.md` file, with one table, like this one:

## CodiMD basics

defaultNotePath can't be set from env-vars

| config file         | environment              | example value                                            | description                                                                                                                                                                                                |
| ------------------- | ------------------------ | -------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| allowPDFExport      | `CMD_ALLOW_PDF_EXPORT`   | `true` or `false`                                        | Enable or disable PDF exports                                                                                                                                                                              |
| db                  | `CMD_CONFIG_FILE`        | `/path/to/config.json`                                   | optional override for the path to CodiMD's config file                                                                                                                                                     |
| dbURL               | `CMD_DB_URL`             | `mysql://localhost:3306/database`                        | Set the db in URL style. If set, then the relevant `db` config entries will be overridden.                                                                                                                 |
| loglevel            | `CMD_LOGLEVEL`           | `info`, `debug` ...                                      | Defines what kind of logs are provided to stdout.                                                                                                                                                          |
| forbiddenNoteIDs    | `CMD_FORBIDDEN_NOTE_IDS` | `'robots.txt'`                                           | disallow creation of notes, even if `CMD_ALLOW_FREEURL` is `true`                                                                                                                                          |
| imageUploadType     | `CMD_IMAGE_UPLOAD_TYPE`  | `imgur`, `s3`, `minio`, `lutim` or `filesystem`          | Where to upload images. For S3, see our Image Upload Guides for [S3](guides/s3-image-upload.md) or [Minio](guides/minio-image-upload.md), also there's a whole section on their respective env vars below. |
| sourceURL           | `CMD_SOURCE_URL`         | `https://github.com/codimd/server/tree/<current commit>` | Provides the link to the source code of CodiMD on the entry page (Please, make sure you change this when you run a modified version)                                                                       |
| tooBusyLag          | `CMD_TOOBUSY_LAG`        | `70`                                                     | CPU time for one event loop tick until node throttles connections. (milliseconds)                                                                                                                          |
| `staticCacheTime`   |                          | `1 * 24 * 60 * 60 * 1000`                                | static file cache time                                                                                                                                                                                     |
| `heartbeatInterval` |                          | `5000`                                                   | socket.io heartbeat interval                                                                                                                                                                               |
| `heartbeatTimeout`  |                          | `10000`                                                  | socket.io heartbeat timeout                                                                                                                                                                                |
| `documentMaxLength` |                          | `100000`                                                 | note max length                                                                                                                                                                                            |

Would you be interested in such pull request?

**Comment by ErikMichelson** [comment]
Before spending time on that: I did something like that somewhere in the past and it looks as a draft like [this](https://erikmichelson.github.io/codimd/#/config/env). 
BUT be careful: That's not the complete/correct documentation and not officially supported.

**Comment by oupala** [comment]
Good news, that's sign that I'm not the only one missing some documentation.

I would also add another column which would be the default value, in addition to example values.

**Comment by oupala** [comment]
As a conclusion, the configuration file path is working as intented. I will then close this issue.

However, it is not possible to override the database configuration in the configuratrion file when using a container as the entrypoint is waiting for an environment variable and sets a default hard-coded variable when there is no environment variable. I'm discussing this in another issue (codimd/container#114).
