### ISSUE TITLE
Update MathJax to 3.0.5

### ISSUE THREAD

**Issue by codingHahn** [codimd/server#374]
I want to update the bundled MathJax to the new version. The problem is that they switched to a modular architecture that requires us to build a custom MathJax build. They have a few prebuilt ones, but they don't fully support our needs (there is no build that has the input components tex and asciimath). 
How should we implement this? Perhaps through a submodule where we build our config during yarn install? Is there a new ideomatic way?

**Comment by codingHahn** [comment]
A new way I have found is with this guide https://docs.mathjax.org/en/latest/web/webpack.html#building-a-custom-component

Lets see if I can make this work

**Comment by SISheogorath** [comment]
I wouldn't like to implement anything entirely new into the 1.6.X releases. This should go into the newer frontend developed by @codimd/frontend that will hit CodiMD in 2.0 :)

**Comment by codingHahn** [comment]
I would like to help, but know next to nothing of webdev. If I would manage to provide a working PR here that is not too compicated, could you merge it as reference for later implementation in codimd/frontend?

**Comment by codingHahn** [comment]
Never mind. MathJax has quite a few breaking changes and building a version with asciimath, tex-full and chtml output cost me a day and I couldn't get it to work with codimd yet. As much as I had hoped for MathJax 3 in the current CodiMD, I cannot do it. I thought it would be easier.

**Comment by davidmehren** [comment]
We already have #211 to track an upgrade to MathJax 3. Please share your experience with building MathJax with the correct feature-set there, our frontend-team will appreciate that!
