### ISSUE TITLE
CodeMirror config: inputStyle: 'textarea' breaks Backspace on mobile

### ISSUE THREAD

**Issue by inducer** [codimd/server#381]
I have observed that editing in every (Android) mobile browser I've tried (Chrome, Firefox, Firefox Preview, Firefox Focus) doesn't seem to work well: Backspace doesn't seem to do anything.

I have also discovered a potential fix: Things start behaving as expected when `inputStyle: 'textarea'` is removed from the CodeMirror config [here](https://github.com/codimd/server/blob/49de5f5bd6239354d98b424804951974588ab25e/public/js/lib/editor/index.js#L574). When that is removed, edits from mobile seem to propagate only after some delay/when moving the cursor. That's the only adverse effect of removing it that I've observed so far, and that certainly preferable (to me) to not being able to delete previously entered text. The [CodeMirror docs for `inputStyle`](https://codemirror.net/doc/manual.html#option_inputStyle) certainly make it sound like the default (`contenteditable`) is preferred over `textarea` precisely because mobile/IME support is better.

As as result I'm wondering: Why is that setting there? Is there any reason why it shouldn't be removed?

**Comment by ErikMichelson** [comment]
> Backspace doesn't seem to do anything.

See #71

**Comment by inducer** [comment]
Hmm, after some time with `inputStyle: 'contenteditable'`, I'm less convinced. Editing is pretty glitchy (bits of words disappear and reappear), and the editor sometimes scrolls to the top of the document randomly. I'm less convinced now that this is a good idea.
