### ISSUE TITLE
Suggestions, Arguments for better note management.

### ISSUE THREAD

**Issue by rustysys-dev** [codimd/server#383]
I know there is already a bit of work being done towards reworking the file management capabilities of CodiMD, but they are not inclusive of what I would like to propose.  I have been a user of CodiMD for nearly 2 years now, and I love it, there are no other libre solutions on the market that do as good a job.

That being said, the largest issue I have is handling note management and would like to suggest/discuss the following points of possible improvement.  

- Allow assigning users to groups
    - raises the question of who can add users to a group and when... but for now...
- Ability to assign notes to a group, and user private note not explicitly assigned
- A page (My Notes) to list notes that a user has access to (not just history) 
- Allow users to view notes assigned to groups they are a member of.
- (possibly) allow separation of notes by group

I believe that implementing the above should sufficiently solve many of the organizational/collaborative issues currently faced.

It should IMHO close the following related cases.

Related issues: #53 #54 #55 #163

**Comment by SISheogorath** [comment]
Generally speaking, I would recommend to push those ideas to: https://community.codimd.org/t/your-plans-for-version-2-0/81

But huge :+1: for the ideas. We are currently working on the basement for further work towards groups and similar details. I can't say 2.0 will provide that already, but it'll definitely lay out the groundwork for it and it's on our list for things we want to make happen.

**Comment by rustysys-dev** [comment]
@SISheogorath  Thanks for the response! That was just the information I was looking for, I will leave a memo there just to add my voice, but it seems as you mentioned that the basic concepts to realize my bullet points have been mentioned. :heart:

**Comment by SISheogorath** [comment]
I'll close this one in favor of the forum post
