### ISSUE TITLE
sign-in modal is too small depending on the login string size

### ISSUE THREAD

**Issue by oupala** [codimd/server#386]
Sign-in modal is too small depending on the login string size. For example if the OIDC login system label is "a much too long label", then the login string will be "Sign in via a much too long label":

![screenshot with small modal](https://user-images.githubusercontent.com/13458743/83746372-481a2b80-a65f-11ea-8124-2284dd44596d.png)

I can see that the template is using a `modal-sm` class:

https://github.com/codimd/server/blob/49de5f5bd6239354d98b424804951974588ab25e/public/views/shared/signin-modal.ejs#L3

Whereas it could use a larger modal for better display:

![screenshot with large modal](https://user-images.githubusercontent.com/13458743/83746662-b4952a80-a65f-11ea-8b3f-44b796d98e18.png)

Should I open a pull request for this change?

**Comment by SISheogorath** [comment]
I think the @codimd/frontend has already been working on recreating the login page. They can probably tell you whether such a change is still needed or will be obsolete with 2.0 anyway :)

**Comment by ErikMichelson** [comment]
The new react-frontend has its own login page (no modal) where the error should not occur.

![image](https://user-images.githubusercontent.com/52606896/83750897-443dd780-a666-11ea-9e77-e37a29ef16af.png)

**Comment by oupala** [comment]
Great!

It could be a small fix for the upcoming 1.6.1 release. By the way, when will this 1.6.1 release be released?

**Comment by ErikMichelson** [comment]
On the other hand it seems to be just changing the size of the modal in 1.6 frontend, so maybe as a temporary fix for 1.6.1 it wouldn't be a bad idea.

**Comment by mrdrogdrog** [comment]
Well yes okay. Changing the modal size is just setting another bootstrap class. My last comment was related to "create the new login page for 1.6.1"

**Comment by SISheogorath** [comment]
I would like to avoid having this going into 1.6.1. To me this is not a fix, but a change and therefore would go into a minor version instead of a patch version. Let's just move this to 2.0 with the new login page and things should be fine :)

**Comment by oupala** [comment]
As you prefer. But I volunteer in making this pull request for 1.6.1.

In fact, it depends when the 2.0 should be released. In the meantime, I'd like to ease the use of codimd. We could also think about a 1.7.0 version, with this pull request.

**Comment by ErikMichelson** [comment]
One could argue if it's a bugfix or not. If we say _"Fixing improper displaying of custom auth provider labels"_ it sounds more as a fix to me and especially because it's only changing one css-class it doesn't seem to me as a feature.
But you decide at last @SISheogorath.

**Comment by oupala** [comment]
I would also consider this as a fix as the current situation is buggy, preventing from displaying the whole label.

**Comment by SISheogorath** [comment]
So I did some research and to be honest, to get this toward something that looks properly, we need to introduce a new CSS class, change the modal size, test it on all screen sizes, …

I don't think it's worth that effort especially since we could spend that time way better on the 2.0 development.

**Comment by ErikMichelson** [comment]
I didn't know that there are only two sizes for modals built-in and have just seen how it would look like with the large modal. It would make the UI less intuitive in my opinion. Therefore I agree with @SISheogorath that the work on it is not worth it.

**Comment by oupala** [comment]
Ok, let's follow you're opinion on that.
