### ISSUE TITLE
`js-sequence-diagrams@1000000.0.6` has been unpublished and replaced by a security holding package

### ISSUE THREAD

**Issue by Ma27** [codimd/server#39]
The dependency [`js-sequence-diagrams`](https://github.com/codimd/server/blob/502c70008e3a1bf61730a5013b274e934c572b6e/package.json#L58) has been replaced [by a security holding package](https://www.npmjs.com/package/js-sequence-diagrams) in the NPM registry.

It's also worth noting that [the upstream repo (bramp/js-sequence-diagrams)](https://github.com/bramp/js-sequence-diagrams) didn't maintain the NPM package, in fact they only supported Bower builds (https://github.com/bramp/js-sequence-diagrams/issues/212).

**Comment by ccoenen** [comment]
Thank you for the notification, we're currently looking how to fix this. We don't want to introduce bower, but we also don't want to break existing pads. If you have any ideas for a more permanent fix, You're very welcome to [join our Matrix channel](https://riot.im/app/#/room/#codimd:matrix.org) to discuss possibilities.
