### ISSUE TITLE
Replace or remove `request`

### ISSUE THREAD

**Issue by davidmehren** [codimd/server#394]
In `lib/response.js` we use the [deprecated](https://github.com/request/request/issues/3142) `request` library.

We should either remove it or replace it with an alternative. Some of them are listed in https://github.com/request/request/issues/3143

**Comment by ccoenen** [comment]
this has been mentioned in #269, would you say this is a duplicate, or do you think this is a separate issue because of its 2.0 focus?

**Comment by davidmehren** [comment]
Well, using the search before opening a new issue might be a good idea next time 😇
