### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by newpost** [codimd/server#403]
addScript.js?f2b5:8 [Script Loader] ReferenceError: require is not defined
    at eval (eval at module.exports (addScript.js?f2b5:27), <anonymous>:3:16)
    at eval (<anonymous>)
    at module.exports (addScript.js?f2b5:20)
    at eval (inline-attachment.js?acb2:1)
    at Object../node_modules/script-loader/index.js!./public/vendor/inlineAttachment/inline-attachment.js (index-pack.js:11453)
    at __webpack_require__ (index-pack.js:20)
    at Object.8 (index-pack.js:12477)
    at __webpack_require__ (index-pack.js:20)
    at index-pack.js:84
    at index-pack.js:87
![image](https://user-images.githubusercontent.com/1679093/84592450-63afde00-ae78-11ea-90a5-1eb11b0a94c2.png)

**Comment by newpost** [comment]
![image](https://user-images.githubusercontent.com/1679093/84592495-bdb0a380-ae78-11ea-8d20-c33a71565d8a.png)

**Comment by DerMolly** [comment]
I guess you started the master branch on your local machine?

**Comment by newpost** [comment]
是的

**Comment by newpost** [comment]
yes@DerMolly

**Comment by SISheogorath** [comment]
@newpost it would be very useful, if you could provide the steps you've taken that broad you to this point. Then other people can start following those or maybe already notice a possible mistake.

The easiest way to find the steps you have taken is using the history command and copy the commands you have used in which order to come to this point. :)

**Comment by newpost** [comment]
https://github.com/codimd/server/blob/master/docs/setup/manual-setup.md#instructions 
Follow this file step by step

**Comment by SISheogorath** [comment]
Ah, that basically explains the whole problem. We don't support Windows as development environment. But you can try using [Ubuntu in WSL](https://ubuntu.com/wsl) which might works :)

We should probably point that out somewhere :thinking:

**Comment by newpost** [comment]
Where do you mention that Windows development is not supported? I didn't notice where it was mentioned? @SISheogorath

**Comment by SISheogorath** [comment]
We never mention it in the docs, which I tried to point out by adding "We should probably point that out somewhere". But when you check the history of the community chat, you should be able to find some efforts to get CodiMD running on Windows, without a lot of success.

It's an application that focuses on Linux for development. And while it would be of course great when it also runs on Windows, no one has yet invested any time to get it running on Windows and we will definitely not recommend Windows as a production environment.
