### ISSUE TITLE
404 on link

### ISSUE THREAD

**Issue by EvilOlaf** [codimd/server#415]
Hey there,

https://github.com/codimd/server/blob/master/docs/setup/manual-setup.md

In step 4 and 5 of `Instructions` both `here` lead into 404 error.

**Comment by SISheogorath** [comment]
Thanks for the hint! Seems seems like the latest documentation changes were not reflected in all docs. @oupala could youncheck the doc links and send a PR, that would be awesome :)

**Comment by oupala** [comment]
I've just done it on #416.

**Comment by EvilOlaf** [comment]
You're welcome.

**Comment by SISheogorath** [comment]
Closed by #416
