### ISSUE TITLE
End-to-end encryption

### ISSUE THREAD

**Issue by darkdragon-001** [codimd/server#420]
I was wondering, if end-to-end encryption is possible. While it is clearly possible for client-to-client communication, I was wondering if patches are applied on the server side or if they are just stored as is and replayed when a new client connects.

**Comment by ccoenen** [comment]
The server also applies the Operational Transform instructions. The document is stored in the database at regular intervals from the version the server "knows". So it would at least be some amount of work to change this.

[Cryptpad](https://cryptpad.fr/), for example, **has** end-to-end support, so we know it **is** possible. But I have never looked at their implementation.

**Comment by ccoenen** [comment]
My personal solution to this is: I run my own setup, so I don't have to trust any third-party admin. If you're somwewhat familiar with docker, this is very easy to host. The transport is, of course, usually tls encrypted (either by codimd or, more commonly, by your front-end proxy like traefik, nginx or apache).

**Comment by darkdragon-001** [comment]
Thanks four your hint. Cryptpad published a [paper](https://transitiontech.ca/assets/private-document-editing-with-some-trust-DRAFT-1.2.pdf) which describes their architecture. Basically, the clients send their encrypted patches, the server stores a chain of patches and every 50th path basically replaces the whole document. This requires a stable reconciliation protocol. So I assume it is out of scope for CodiMD. While self-hosting with over-the-wire encryption is _quite_ good, I prefer to choose zero-knowledge architecture whenever possible.

From my impression, CryptPad is a really cool piece of software and the people working on it really know what they are doing. I was just looking for a more lightweight solution. That's why I added encryption to [pereorga/minimalist-web-notepad](https://github.com/pereorga/minimalist-web-notepad/pull/43) and [petercunha/Pad](https://github.com/petercunha/Pad/pull/16). They are not suitable for real-time collaboration since they basically replace the whole document when its content is changed.

**Comment by ccoenen** [comment]
I think we will eventually work on this. I'm not sure when, though. If you can contribute to that end, come and say 'hi' on our matrix chat :-)

I'd even go as far as keeping this open, what's your opinion @SISheogorath?

**Comment by SISheogorath** [comment]
As much as I would like E2EE to become an option, I don't see it. We do a lot of automation and optimization around the fact that we know the content on the server side. Starting from the new API, over SSR in some places to the simple fact we embed note content in various ways which will make such implementations a lot more complex.

Cryptpad exists and is a very good piece of software and I encourage people who want to use E2EE to use it. I don't think it makes sense for us to:

1. Jump in their work domain
2. assume we could do it better
3. provide E2EE when we serve the frontend from the same backend that E2EE claims to protect us from.

What concerns can be solved that E2EE claims to solve but can be solved in a different way as well? Encryption at rest. 

This can be solved by full disk encryption. If we don't want to rely on that, we can think of using a [KDF](https://en.wikipedia.org/wiki/Key_derivation_function) to generate a key that is used for encryption of a note-key for each user individually. Means the content of the node would be transparent to the node process on the backend, but be stored encrypted with a note-individual key that is encrypted with a user-individual key that is derived from user passwords on sign-in. Obviously this would break sessions on restarts of the application but solve the problem. But it has nothing to do with E2EE except it solves the only realistic and most concerned scenario people have when they want a webapp to perform E2EE while storing the data for them as well as serving the frontend.
