### ISSUE TITLE
workers/dmpWorker ignores loglevel setting

### ISSUE THREAD

**Issue by dalcde** [codimd/server#433]
This is tested on `release/2.0.x`. `workers/dmpWorker.ts` logs a lot of messages at the `debug` level, and this is always printed regardless of the `loglevel` setting. The reason is that this code runs as a child process instead of in the main thread, and uses a different global instance of the logger. This is a fresh global instance with the default `loglevel`, which is `debug`.

This can be reproduced by looking at notes revisions. This leaks notes contents into the logs, which is Bad.

**Comment by dalcde** [comment]
In general, `winston` does not support multithreaded applications: https://github.com/winstonjs/winston/issues/80

**Comment by dalcde** [comment]
One possible solution is to let `dmpWorker.ts` send the log message back to the main thread and let the main thread do the actual logging.

**Comment by davidmehren** [comment]
I'm confused, shouldn't GitHub close this issue after #434 was merged?
Anyway, thanks again for the fix!

**Comment by SuperSandro2000** [comment]
It only does this if the branch is master by default. I think there is a setting which enables it on non default branches,.
