### ISSUE TITLE
Upper most indentation of lists not reachable in Vim mode

### ISSUE THREAD

**Issue by spickartz** [codimd/server#435]
I can change the indentation level by pressing `Tab` and to go back I have to use `Shift+Tab`. However, the latter only works up to the first indentation level in Vim mode. To reach the upper most level, I have to enable Sublime mode. I tested this on https://demo.codimd.org. 

Is this a known limitation of the Vim mode?

**Comment by DerMolly** [comment]
I am not to sure, but I think Vim mode is a feature of [codemirror](https://github.com/codemirror/CodeMirror) we just use. That may be fixed with a newer version of codemirror.

**Comment by spickartz** [comment]
Thanks for the feedback! Shall I open an according issue in the upstream codemirror repository?

**Comment by DerMolly** [comment]
I'd suggest searching if anyone else opened an issue about that first, but yes I think that's the way to go...
If you open something or find an issue feel free to link it here for the next user with the problem.

**Comment by davidmehren** [comment]
I'm going to close this, as there is really nothing we can do about this.
Sadly, [CodeMirror states](https://codemirror.net/demo/vim.html) that the VIM bindings are currently unmaintained, so a solution seems unlikely. :/
As a workaround, you should be able to use `<<` and `>>` to [indent whole lines](https://github.com/codenvy-legacy/plugin-editor-codemirror/wiki/Vim-keymap#whole-line-variants).
