### ISSUE TITLE
Choose Express annotation library

### ISSUE THREAD

**Issue by davidmehren** [codimd/server#444]
Part of #443

To make writing controllers easier, we could take advantage of annotations. Multiple libraries providing such functionality are available. We need to choose one.

- [typestack/routing-controllers](https://github.com/typestack/routing-controllers)
- [overnightJS](https://github.com/seanpmaxwell/overnight)
- [typescript-rest](https://github.com/thiagobustamante/typescript-rest)

**Comment by DerMolly** [comment]
Looking at the proposed libraries, I think we should go with `typestack/routing-controllers` as it has a nice feature set and seems widely adopted, which should be helpful both from a 'easy to contribute' and from a 'easy to get support' aspect.

**Comment by davidmehren** [comment]
In #443 we decided to go with NestJS, which uses [typestack/routing-controllers](https://github.com/typestack/routing-controllers).
