### ISSUE TITLE
Choose dependency injection library

### ISSUE THREAD

**Issue by davidmehren** [codimd/server#445]
Part of #443

We want to use dependency injection in 2.0 and need to choose a library. Candidates are:

- [typescript-ioc](https://github.com/thiagobustamante/typescript-ioc)
- [tsyringe](https://github.com/microsoft/tsyringe)
- [typedi](https://github.com/typestack/typedi)

**Comment by davidmehren** [comment]
Note that I didn't include InversifyJS because the maintainer [seems to have disappeared](https://github.com/inversify/InversifyJS/issues/1158).

**Comment by davidmehren** [comment]
typedi also isn't well maintained, the last commit was in january of last year. :disappointed: 

That leaves typescript-ioc and Microsoft's tsyringe. Tsyringe only supports constructor injection, but that *should* be enough for our use-case. It also handles circular dependencies, which [typescript-ioc doesn't](https://github.com/thiagobustamante/typescript-ioc#restrictions). I would also guess that something published by Microsoft has a lower probability of suddenly becoming abandoned.

I therefore favor tsyringe.

**Comment by davidmehren** [comment]
In #443 we decided to go with NestJS, which has it's own DI system.

**Comment by pauchiner** [comment]
Hi, I'm having trouble using a dependency injection library with React Native, all the packages listed in this issue are out of date and [@nestjs](https://github.com/nestjs/nest) doesn't work well in React Native (At least in my experience).

Does anyone know why no one is updating these kinds of libraries?
Is there a better solution to inject dependencies without going through libraries?

I'm thinking of using [typedi](https://github.com/typestack/typedi/tree/develop) but I don't know if this will be a problem in the future.
