### ISSUE TITLE
Choose validation library/strategy

### ISSUE THREAD

**Issue by davidmehren** [codimd/server#448]
Part of #443

To improve type safety, we plan to validate all externally generated data (like JSON from an HTTP request). Ideally this validation takes place against a TypeScript class.

Based on our current state of research, we have concluded that there is no simple way of doing that. Some kind of additional annotation to provide validation information is always neccessary. Also, most libraries don't have an easy way of doing "here is some JSON, if it's valid please give me an instance of the class". Therefore, the current plan is to use a `fromJSON(json: string): ClassName` method in the DTOs, which get the JSON string, perform validation (either manually or with one of the libraries) and return a instance.

Possible libraries include:
- [io-ts](https://gcanti.github.io/io-ts/)
- [validator.js](https://github.com/validatorjs/validator.js)
- [typestack/class-validator](https://github.com/typestack/class-validator)

**Comment by SISheogorath** [comment]
Might this goes into the right direction: https://www.npmjs.com/package/typescript-json-schema

We could generate the json schemas from our classes and then throw them into a jsonschema valdiator. Would make the whole thing rather easy, just the build process is a bit annoying.

**Comment by DerMolly** [comment]
I think we explicitly didn't want to go this route, because than you need to maintain two representations of an DTO instead of one.

**Comment by davidmehren** [comment]
In #443 we decided to go with NestJS, which uses [typestack/class-validator](https://github.com/typestack/class-validator).
