### ISSUE TITLE
Disable HTTP Access log

### ISSUE THREAD

**Issue by fabiodcorreia** [codimd/server#449]
Hi,

It's possible to disable the http access log? I tried to put the log level on warn but the access logs still show on the logs.

```
2020-07-12T19:34:57.711Z info: 	172.18.0.1 - - [12/Jul/2020:19:34:57 +0000] "GET / HTTP/1.1 .....
```

**Comment by davidmehren** [comment]
When using `"loglevel": "warn"` in my `config.json`, the access log isn't displayed for me.
Are you sure your `NODE_ENV` setting (e.g. `development` or `production`) matches the config section you changed the setting in?

You are also welcome to join [our chat](https://riot.im/app/#/room/#codimd:matrix.org) for more interactive help.

**Comment by fabiodcorreia** [comment]
I'm using the ENV CMD_LOG_LEVEL, the NODE_ENV I will double check. Maybe I missed something on my setup. I will return with follow-up.

**Comment by fabiodcorreia** [comment]
Ok so, if I set the value directly on the config.json it works but if I use the ENV it doesn't work.

**Comment by ErikMichelson** [comment]
I just [looked it up](https://github.com/codimd/server/blob/master/lib/config/environment.js#L12): The environment variable is called `CMD_LOGLEVEL` (without the third underscore).

**Comment by fabiodcorreia** [comment]
Correct, the ENV name is without _ I will now refer to that file in the future. Thanks.
