### ISSUE TITLE
How to config white listed domain names for CORS on config.json

### ISSUE THREAD

**Issue by chenboshiun** [codimd/server#450]
Hello CodiMD Support:

We deploy Azure Active Directory Application Proxy for CodiMD

 But user can't normal login and access CodiMD after 1 - 2 hours

We and Azure Support discover CORS policy issue via Google Chrome Console

![image024](https://user-images.githubusercontent.com/65486072/87401530-d5508880-c5ec-11ea-8a3c-ca7cbbac1fd9.png)

How to config white listed domain names for CORS on config.json or fix this issue ?

Thanks :)

**Comment by chenboshiun** [comment]
[Understand and solve Azure Active Directory Application Proxy CORS issues](https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/application-proxy-understand-cors-issues)

**Comment by davidmehren** [comment]
Disclaimer: I have no idea how this Azure stuff works.

My theory is the following:
- After 1 - 2 hours, the Azure AD Proxy login expires and the proxy redirects all requests to the login page.
- This redirect happens in an XMLHttpRequest, therefore CORS rules apply.
- As `login.microsoftonline.com` obviously does not have your CodiMD domain in its `Access-Control-Allow-Origin` header, the request fails.

So as far as I can see, this has nothing to do with our CORS rules, but with the Azure Proxy which decides to suddenly redirect requests to `login.microsoftonline.com`. You probably have to ask Azure support on how to solve this.

**Comment by davidmehren** [comment]
Alright, I'll close this for now. If you have any more questions, feel free to ask them in the [community chat](https://riot.im/app/#/room/#hedgedoc:matrix.org)
