### ISSUE TITLE
Email sign-in doesn't work

### ISSUE THREAD

**Issue by mthld** [codimd/server#456]
Hello,

When I try to sign-in with email on my instance (running on the `master` branch) it doesn't work. I'm just being redirected to the homepage (HTTP 302).
Users have been created with the `bin/manage_users` utility.

Here is the config.json file:
```
{
    "production": {
        "domain": "REDACTED",
        "allowOrigin": "REDACTED, REDACTED",
        "useSSL": false,
        "protocolUseSSL": true,
        "host": "localhost",
        "port": "3330",
        "sessionSecret": "REDACTED",
        "loglevel": "debug",
        "hsts": {
            "enable": true,
            "maxAgeSeconds": 31536000,
            "includeSubdomains": true,
            "preload": true
        },
        "csp": {
            "enable": true,
            "directives": {
            },
            "upgradeInsecureRequests": "auto",
            "addDefaults": true,
            "addDisqus": false,
            "addGoogleAnalytics": false
        },
        "db": {
            "username": "REDACTED",
            "password": "REDACTED",
            "database": "REDACTED",
            "host": "localhost",
            "port": "5432",
            "dialect": "postgres"
        },
        "allowAnonymous": false,
        "email": true,
        "allowEmailRegister": false,
        "linkifyHeaderStyle": "gfm"
    }
}
```

The application is served by Nginx, here is the vhost location part:
```
location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://localhost:3330;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_next_upstream error timeout http_502 http_503 http_504;
    }
```

Here is the debug log when I try to login:
```
2020-07-23T07:32:59.478Z info:  serializeUser: caf45da5-5a9d-4ff3-b85a-90f5ec0b9426
2020-07-23T07:32:59.491Z info:  127.0.0.1 - - [23/Jul/2020:07:32:59 +0000] "POST /login HTTP/1.1" 302 96 "https://REDACTED/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15"
```

Thanks in advance for your help.

**Comment by mthld** [comment]
I'm digging a bit into this, on my browser web console I checked the request made to `/login` and the address mentioned in the header seems wrong: `127.0.0.1:6501`

**Comment by mthld** [comment]
I found the issue in the Nginx vhost config, here is a working one:
```
location / {
        proxy_pass http://localhost:3330;
	proxy_redirect    off;
  	proxy_set_header  Host $host;
  	proxy_set_header  X-Real-IP $remote_addr;
	proxy_set_header  X-Forwarded-Proto $scheme;
	proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
 	proxy_set_header  X-Forwarded-Host $server_name;
  
	proxy_http_version 1.1;
 	proxy_set_header Upgrade $http_upgrade;
 	proxy_set_header Connection "upgrade";

  	proxy_read_timeout 300;
  	proxy_connect_timeout 300;
    }
```

Maybe it'll be usefull if this is documented somewhere, a lot of people must be running CodiMD behind a reverse proxy.

**Comment by pinpox** [comment]
> I found the issue in the Nginx vhost config, here is a working one:
> 
> ```
> location / {
>         proxy_pass http://localhost:3330;
> 	proxy_redirect    off;
>   	proxy_set_header  Host $host;
>   	proxy_set_header  X-Real-IP $remote_addr;
> 	proxy_set_header  X-Forwarded-Proto $scheme;
> 	proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
>  	proxy_set_header  X-Forwarded-Host $server_name;
>   
> 	proxy_http_version 1.1;
>  	proxy_set_header Upgrade $http_upgrade;
>  	proxy_set_header Connection "upgrade";
> 
>   	proxy_read_timeout 300;
>   	proxy_connect_timeout 300;
>     }
> ```
> 
> Maybe it'll be usefull if this is documented somewhere, a lot of people must be running CodiMD behind a reverse proxy.

Which of those settings fixed it for you? I'm having a similar issue, I click login but am redirected to the landing page without being actually logged in. No errors to be found anywhere

**Comment by mthld** [comment]
> Which of those settings fixed it for you? I'm having a similar issue, I click login but am redirected to the landing page without being actually logged in. No errors to be found anywhere

No idea, I don't use this software anymore. But reading my first post I can guess `proxy_redirect    off;` was missing. Does adding it works for you?

**Comment by rigwild** [comment]
> Which of those settings fixed it for you? I'm having a similar issue, I click login but am redirected to the landing page without being actually logged in. No errors to be found anywhere

For me it was `proxy_set_header X-Forwarded-Proto $scheme;` that was missing. After adding it, it works :)

```
upstream hedgedoc.example.com {
  server 127.0.0.1:3000;
  keepalive 8;
}

server {
  listen 80;

  server_name hedgedoc.example.com;
  access_log /var/log/nginx/hedgedoc.example.com_access.log;
  error_log /var/log/nginx/hedgedoc.example.com_error.log warn;

  location / {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header X-NginX-Proxy true;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_pass http://hedgedoc.example.com/;
    proxy_redirect off;
  }
}
```
