### ISSUE TITLE
config.json seems to be ignored after upgrading to 1.3.2 with new repo

### ISSUE THREAD

**Issue by tcharlss** [codimd/server#47]
Hi,

We are using our own instance of CodiMd on a Debian 9 server.

Everything was working fine until we tried to upgrade from v1.2x to v1.3.2 yesterday.
We switched to the new repo and followed the manual: ["How to upgrade your installation"](https://github.com/codimd/server/blob/master/docs/setup/manual-setup.md#how-to-upgrade-your-installation).

There were a few dependancies issues, but we managed to fix them.
Now when we launch the app.js, we get the following error :

```console
codimd@codimd:/opt/codimd$ node app.js
2019-04-15T22:01:50.771Z warn: 	Neither 'domain' nor 'CMD_DOMAIN' is configured. This can cause issues with various components.
Hint: Make sure 'protocolUseSSL' and 'urlAddPort' or 'CMD_PROTOCOL_USESSL' and 'CMD_URL_ADDPORT' are configured properly.
2019-04-15T22:01:50.774Z warn: 	Session secret not set. Using random generated one. Please set `sessionSecret` in your config.js file. All users will be logged out.
2019-04-15T22:01:51.505Z info: 	dmp worker process started
>> WARNING: SQLite does not support TEXT with options. Plain `TEXT` will be used instead.
```
 
But all the options mentioned in this error message are defined in our config.json file, and furthermore we are using Mysql, not Sqlite.
It seems that our config file is now entirely ignored.
The permissions on this file have not changed, the owner is still the user codimd, and it is readable.

So we are a bit at a loss atm, any help will be greatly appreciated :)

**Comment by ccoenen** [comment]
Hi, welcome to CodiMD! We're currently discussing this issue in our matrix channel. This has already lead to an overhaul of the update instructions (not yet in the main repository, but can be seen here: https://github.com/codimd/server/pull/45

**Comment by tcharlss** [comment]
Thanks for your quick feedback.
The new instructions solved our issues :)
