### ISSUE TITLE
support for webp animated format

### ISSUE THREAD

**Issue by zeigerpuppy** [codimd/server#483]
It would be great to be able to upload and play webp animated images just like we do for other image formats.

**Comment by davidmehren** [comment]
Does animated WebP also use the `image/webp` MIME type?
If yes, we already support that since #534

**Comment by mrdrogdrog** [comment]
According to the [google docs for webp](https://developers.google.com/speed/webp/docs/riff_container) : yes

**Comment by davidmehren** [comment]
Nice! So we are done here and animated WebP will be supported by 2.0. :tada: :rocket:
