### ISSUE TITLE
Google auth not actually logging in

### ISSUE THREAD

**Issue by aksdb** [codimd/server#492]
I run CodiMD in k8s using the current docker image `quay.io/codimd/server:1.6.0`.

The environment variables set are:
```
CMD_DOMAIN=my.domain
CMD_PROTOCOL_USESSL=true
CMD_URL_ADDPORT=false
CMD_ALLOW_ANONYMOUS=false
CMD_ALLOW_ANONYMOUS_EDITS=true
CMD_EMAIL=false
CMD_GOOGLE_HOSTEDDOMAIN=my.domain
CMD_GOOGLE_CLIENTID=***
CMD_GOOGLE_CLIENTSECRET:***
```

When I login, I get redirected to the Google login page (fine), and then redirected back to CodiMD (also fine), but then nothing more happens. I am back at the start page and still not logged in.

In the server log I see:

```
Sep 3, 2020 @ 17:56:41.105  2020-09-03T15:56:41.105Z info:  000.000.000.000 - - [03/Sep/2020:15:56:41 +0000] "GET /auth/google/callback?code=*******************&scope=profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile HTTP/1.1" 302 100 "-" "MyUserAgent"

Sep 3, 2020 @ 17:56:41.121  2020-09-03T15:56:41.121Z info:  Executing (default): SELECT "sid", "expires", "data", "createdAt", "updatedAt" FROM "Session" AS "Session" WHERE "Session"."sid" = '11111111111111111111';

Sep 3, 2020 @ 17:56:41.123  2020-09-03T15:56:41.123Z info:  Executing (default): INSERT INTO "Session" ("sid","expires","data","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5) RETURNING *;

Sep 3, 2020 @ 17:56:41.194  2020-09-03T15:56:41.194Z info:  000.000.000.000 - - [03/Sep/2020:15:56:41 +0000] "GET / HTTP/1.1" 304 - "-" "MyUserAgent"

Sep 3, 2020 @ 17:56:41.318  2020-09-03T15:56:41.317Z info:  Executing (default): SELECT "sid", "expires", "data", "createdAt", "updatedAt" FROM "Session" AS "Session" WHERE "Session"."sid" = '22222222222222222222';

Sep 3, 2020 @ 17:56:41.320  2020-09-03T15:56:41.320Z info:  Executing (default): INSERT INTO "Session" ("sid","expires","data","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5) RETURNING *;

Sep 3, 2020 @ 17:56:41.355  2020-09-03T15:56:41.355Z info:  000.000.000.000 - - [03/Sep/2020:15:56:41 +0000] "GET /config HTTP/1.1" 304 - "https://my.domain/" "MyUserAgent"

Sep 3, 2020 @ 17:56:41.669  2020-09-03T15:56:41.532Z info:  000.000.000.000 - - [03/Sep/2020:15:56:41 +0000] "GET /me HTTP/1.1" 304 - "https://my.domain/" "MyUserAgent"
```
(UserAgent, SIDs, Domain and IPs have been replaced)

In the network tools I can see that the call to `/me` returned "forbidden". So somehow it seems like the callback was completely ignored, even though it apparently was received (see logs above).

What could be wrong here? What can I do to further debug/resolve this?

**Comment by SISheogorath** [comment]
Are you running over HTTPS? If not this might be the problem. We currently have a patch for the next version which will fix the cookie policy. The latest(?) Chromium version comes with different cookie policy which will cause problems with authentication when not running over HTTPS.

To verify if this might be related, you could try to build the latest version from master and test it with that one. (Yes, I know, not the greatest solution, but probably worth a try.)

**Comment by aksdb** [comment]
The ingress enables TLS, so all connections are HTTPS. The callback is also correctly using HTTPS.
![image](https://user-images.githubusercontent.com/2435857/92236246-57568280-eeb5-11ea-8fe2-ba5b6daf1903.png)

Anything else I should look out for?

**Comment by SISheogorath** [comment]
You can check if the HTTP connection to the `/me` page contains the authentication cookie that you get on login.

**Comment by aksdb** [comment]
I get a new session id cookie every time, as it seems. Even though I send along the current/last one.
![image](https://user-images.githubusercontent.com/2435857/92300284-e3ba8100-ef59-11ea-9791-03aa42d5eec8.png)
![image](https://user-images.githubusercontent.com/2435857/92300288-e61cdb00-ef59-11ea-8d89-d26fbce8f7a2.png)

The next requests (`/config` and `/me`) are the same. Always sending the cookie from the previous request and getting a new one back.

**Comment by SISheogorath** [comment]
Actually, I can't really explain it in this case, as the sessions are not regenerated on each reload, for obvious reasons they stay the same throughout a session. Is there anything in between your container and your frontend that might strips cookies, because CodiMD doesn't do that itself? Might be some WAF or alike?

**Comment by aksdb** [comment]
Not that I am aware of.
Could it be a problem that CodiMD is running with multiple nodes? If I understand the log output correctly, sessions are stored in the DB, right? So they are synced and it doesn't matter if the load balancer routes the next request to a different node, right?
Can I get CodiMD to log the headers it receives? (to find out if nginx is screwing something up)

**Comment by SISheogorath** [comment]
Oh, don't run multiple instances of CodiMD, it's not built for multi-node setups. Scaling shouldn't be a problem and as long as your database is HA your CodiMD instance will be back in  a matter of seconds in a cluster.

**Comment by aksdb** [comment]
:man_facepalming: Yep, that was it. With only a single node I could immediately log in (I assume the default load balancing strategy is round robin, so being the only user at the moment basically guaranteed that every other requests ends up on the other node.)

So thanks for helping me find my layer-8 problem :smile:
