### ISSUE TITLE
error parsing headers with numbers, error with horizontal rule

### ISSUE THREAD

**Issue by wolftune** [codimd/server#493]
`## 1. Hello`

vs

```
1. Hello
----------
```

They should probably be the same. But here in GitHub, the latter ignores the `-----` part and in CodiMD, that turns into an *extra* horizontal rule. Both make this part of an ordered list. Wheres the one-line has-based markdown recognizes this as h2 and just uses the number as part of the title.

Regardless of solving this, the markdown for horizontal rule is to have blank lines both above and below, so it shouldn't be generated in this case.

Is this an upstream bug to report to a markdown parsing library CodiMD uses?

I noticed that pandoc succeeded in parsing both versions the same way.

**Comment by DerMolly** [comment]
Hey wolftune,

This seems to be a problem with markdown-it at least the same happens on their  [demo page](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%23%23%201.%20Hello%5Cn%5Cnvs%5Cn%5Cn1.%20Hello%5Cn----------%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Afalse%2C%22typographer%22%3Afalse%2C%22_highlight%22%3Afalse%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D).

**Comment by wolftune** [comment]
reported: https://github.com/markdown-it/markdown-it/issues/708
