### ISSUE TITLE
Language-dependent spellcheck

### ISSUE THREAD

**Issue by hydrargyrum** [codimd/server#518]
When editing a document, it's possible to enable spellcheck. However, it's only for English language. When there's a `lang` option set in the [YAML metadata](https://demo.codimd.org/yaml-metadata), the spellchecker should follow that option.

**Comment by DerMolly** [comment]
Thanks for the suggestion!
Could you add this to https://github.com/codimd/react-client/issues/479 as we‘re already discussing solutions there?

**Comment by DerMolly** [comment]
As you commented in the other issue I'll close this one. If you think this should be open, feel free to reopen it.
