### ISSUE TITLE
Authenticate Using Active Directory over LDAPS

### ISSUE THREAD

**Issue by chenboshiun0109** [codimd/server#532]
Hello CodiMD Support:

We want to authenticate using Active Directory over LDAPS, How to config LDAPS and certificate path on config.json

I had tried to config LDAPS and tried to authenticate using Active Directory , but show "502 Bad Gateway" on my browser

```
        "ldap": {
            "providerName": "Tester Group",
            "url": "ldaps://ds.tester.id",
            "bindDn": "CN=Service IT,OU=AADDC Users,DC=ds,DC=tester,DC=id",
            "bindCredentials": "xxxxxxx",
            "searchBase": "OU=AADDC Users,DC=ds,DC=tester,DC=id",
            "searchFilter": "(&(objectcategory=person)(objectclass=user)(|(sAMAccountName={{username}})(mail={{username}})))",
            "useridField": "sAMAccountName"
            "tlsca": [ "/path/to/cert.pem" ]
        },
```

How to fix this problem and resolve this request?

Thanks :)

**Comment by davidmehren** [comment]
Hi!

For support requests we recommend using our [Matrix chat](https://matrix.to/#/#hedgedoc:matrix.org) or  the [community forum](https://community.codimd.org/).  
Please also provide an excerpt of the CodiMD log at the time you encountered the error.

**Comment by chenboshiun0109** [comment]
@davidmehren 

I update config as below:

```
        "ldap": {
            "providerName": "Tester Group",
            "url": "ldaps://ds.testxer.id",
            "bindDn": "CN=Service KKBOX IT,OU=AADDC Users,DC=ds,DC=tester,DC=id",
            "bindCredentials": "xxxxxxxx",
            "searchBase": "OU=AADDC Users,DC=ds,DC=tester,DC=id",
            "searchFilter": "(&(objectcategory=person)(objectclass=user)(|(sAMAccountName={{username}})(mail={{username}})))",
            "useridField": "sAMAccountName",
            "tlsOptions": {
               "ca": "/path/to/xxxxxx.cer"
            }
        },
```

And I run npm start --production, show Error msg as below

```
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1088:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:666:8)
```

**Comment by davidmehren** [comment]
IIRC, we solved this problem in the community chat.

**Comment by saschafoerster** [comment]
Have the same issue. Would be lovely to find the solution here as well. :)

**Comment by bjrne** [comment]
@davidmehren @saschafoerster @chenboshiun0109 Can you share your solutions here in case you found one? I think I am running into the same issue.

**Comment by saschafoerster** [comment]
I switched to Authentik.io in the meantime and use it for SSO: https://docs.goauthentik.io/integrations/services/hedgedoc/
