### ISSUE TITLE
Document whether CodiMD can be run replicated

### ISSUE THREAD

**Issue by haslersn** [codimd/server#540]
I did not find any documentation whether and, if yes, under what circumstances (such as using a shared DB and using a shared FS for the uploads directory) CodiMD can be run replicated.

**Comment by SISheogorath** [comment]
CodiMD can not be run replicated. Your orchestration should make sure that always one, but not more than one instance is running.

The reason is that the application itself keeps some amount of state to allow the live editing feature.

**Comment by haslersn** [comment]
Is it on the roadmap to store the state in Redis?

**Comment by SISheogorath** [comment]
We currently run the demo instance with more than 200 concurrent people editing. Adding redis would make the setup unnecessary complex. At least for 1.x that's not feasible. Maybe @davidmehren has some insight for the 2.0 development and if the framework that will be used for the backend has a simple integration.

**Comment by davidmehren** [comment]
As far as I understand the old realtime code, while a note is edited, the server does two things:
- Distribute incoming OT events to all other clients editing the same note
- Apply OT events to a copy of the note in RAM and persist that to the database every now and then (as revisions)

So as long as clients (and their websockets) accessing the same note are directed at the same backend, load-balancing *might* actually already be possible. But as scalability was a non-issue until now, nobody seems to have bothered to look into that :D

We haven't really started thinking about realtime in 2.0. It will probably work in a similar way as 1.x. When we come to tackle the new realtime code, we will make sure to structure the in-memory state in such a way that it can be moved to Redis (or something similar), should that ever be necessary. Another idea might be to start a new thread for every edited note, but any work into scalability will probably first need someone coming forward with "my instance goes down when X many users use it at the same time".

**Comment by haslersn** [comment]
> So as long as clients (and their websockets) accessing the same note are directed at the same backend, load-balancing _might_ actually already be possible.

By which key do clients need to be partitioned? Is it sufficient to do this special handling for the `/socket.io/` path and use the query parameter `noteId` as the key (where clients with the same value must be directed to the same backend)?

**Comment by haslersn** [comment]
> * Apply OT events to a copy of the note in RAM and persist that to the database every now and then (as revisions)

What if a different backend modified the state of the note in the database in the meantime (i.e. split brain)?

**Comment by davidmehren** [comment]
> Is it sufficient to do this special handling for the /socket.io/ path and use the query parameter noteId as the key (where clients with the same value must be directed to the same backend)?

If you want to play around with load-balancing that is probably a good first bet. Session info is stored into the database, so that should not be a problem. But I really can't say for sure if nothing else in the code needs special handling...

> What if a different backend modified the state of the note in the database in the meantime (i.e. split brain)?

Then...things will break? :smiley:  
1.x really has no provisions for running multiple instances at the same time. In 2.0, we will take care not to do anything that stops us from adding "cluster mode" at a later time, but anything more will have to come in later releases.

**Comment by SISheogorath** [comment]
@haslersn could you share your motivation that makes you requiring more than one instance at the time?

**Comment by haslersn** [comment]
Yes. The motivation is doing

- rolling upgrades and
- Kubernetes node reboots

without downtime. Currently there's a downtime of about 5 seconds when restarting the Kubernetes deployment. (Maybe the downtime can be reduced by adding a [liveness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/), though.

**Comment by davidmehren** [comment]
We have added a section about multiple instances to [our FAQ](https://community.codimd.org/t/frequently-asked-questions/190).
If you would like to contribute towards 0-downtime upgrades, feel free to join our [chat](https://matrix.to/#/#hedgedoc:matrix.org) or open a new issue.
