### ISSUE TITLE
use of credentials in embeded PDF doesn't work 

### ISSUE THREAD

**Issue by zeigerpuppy** [codimd/server#545]
I have a PDF which I'm trying to embed using the syntax:

```
{%pdf https://myserver.net/public/PDF/Document.pdf %}
```

This works.  However, the PDF is stored on a WebDAV server which requires authentication.
When I try to embed the authentication information:

```
{%pdf https://public:public@myserver.net/public/PDF/Document.pdf %}
```

The PDF tag, then doesn't load.

I guess that something is failing in parsing the `user:password@` stanza.

**Comment by SISheogorath** [comment]
This seems to be mainly a regex issue. The regex in question is this one, which doesn't account for URLs that contain login information:

https://github.com/codimd/server/blob/623e77082f59569f98f691be186597894a7c0ea2/public/js/extra.js#L180-L192
