### ISSUE TITLE
OAuth2CustomStrategy.callback 500 error when used with Keycloak

### ISSUE THREAD

**Issue by boardfish** [codimd/server#56]
Seems like Keycloak has a [passport adapter](https://www.npmjs.com/package/@exlinc/keycloak-passport). First question - this doesn't seem to be baked into CodiMD yet, so is there a workaround? Second question - is there a pull request to add OAuth2 support for another provider that I could reference in making my own, if it came to that?

**Comment by boardfish** [comment]
After some digging, I found that there [is actually support for custom OAuth2 providers](https://github.com/codimd/server/blob/master/docs/configuration-env-vars.md#oauth2-login), but my current setup is a touch broken:

```
      - CMD_DB_URL=postgres://hackmd:password@codimd-database:5432/hackmd
      - CMD_OAUTH2_USER_PROFILE_URL=https://keycloak.example.com/auth/realms/test-realm/protocol/openid-connect/userinfo
      - CMD_OAUTH2_USER_PROFILE_USERNAME_ATTR=username
      - CMD_OAUTH2_USER_PROFILE_DISPLAY_NAME_ATTR=username
      - CMD_OAUTH2_USER_PROFILE_EMAIL_ATTR=email
      - CMD_OAUTH2_TOKEN_URL=https://keycloak.example.com/auth/realms/test-realm/protocol/openid-connect/token
      - CMD_OAUTH2_AUTHORIZATION_URL=https://keycloak.example.com/auth/realms/test-realm/protocol/openid-connect/auth
      - CMD_OAUTH2_CLIENT_ID=client-id
      - CMD_OAUTH2_CLIENT_SECRET=cL13nt-s3cr3t
      - CMD_OAUTH2_PROVIDERNAME=Keycloak
      - CMD_DOMAIN=codimd.example.com
      - CMD_PROTOCOL_USESSL=true 
      - CMD_URL_ADDPORT=false
```

With the below set, I can choose my auth provider at the login screen, and I'm redirected to the login page for Keycloak: `https://keycloak.example.com/auth/realms/test-realm/protocol/openid-connect/auth?response_type=code&redirect_uri=https%3A%2F%2Fcodimd.example.com%2Fauth%2Foauth2%2Fcallback&client_id=client-id`. After correctly entering my credentials, I'm redirected back to my CodiMD instance, but I receive a 500 error on return:

```
TypeError: Cannot read property 'toString' of undefined
    at OAuth2CustomStrategy.callback [as _verify] (/codimd/lib/web/auth/utils.js:17:29)
    at /codimd/node_modules/passport-oauth2/lib/strategy.js:202:24
    at /codimd/lib/web/auth/oauth2/index.js:82:5
    at passBackControl (/codimd/node_modules/oauth/lib/oauth2.js:134:9)
    at IncomingMessage.<anonymous> (/codimd/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
2019-04-18T16:52:47.919Z info: 	10.0.5.38 - - [18/Apr/2019:16:52:47 +0000] "GET /auth/oauth2/callback?session_state=<redacted>&code=<redacted> HTTP/1.1" 500 148 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/73.0.3683.75 Chrome/73.0.3683.75 Safari/537.36"
```

I'm rescoping the issue to resolve that, if it's okay. Hopefully it'll still serve as a guide for those who'd like to integrate Keycloak with CodiMD once this issue is fixed.

For some additional info, I'm running CodiMD in Docker as in the `container` repo, and it's behind an NGINX proxy managed through `jwilder/nginx-proxy` with the LetsEncrypt companion.

**Comment by ccoenen** [comment]
We also have a few authentication documentations in this directory: https://github.com/codimd/server/tree/master/docs/guides/auth

The one I'm most familiar with is the nextcloud one: https://github.com/codimd/server/blob/master/docs/guides/auth/nextcloud.md

Feel free to [join our matrix chat](https://riot.im/app/#/room/#codimd:matrix.org) if you want to discuss how to apply this to your scenario! If you wish and have the time, it would be amazing if you could write a howto for your application - you may of course base it on any existing document!

**Comment by boardfish** [comment]
I agree, it'd be better to do that than leave this as the only documentation for this auth provider. But that'll be for naught unless it works. Is there anything you can see missing from my env var setup that might result in the described error?

**Comment by ccoenen** [comment]
the error is created here:

https://github.com/codimd/server/blob/a22c1a9d657cb41068aa5023e63f6251ac16a5c5/lib/web/auth/utils.js#L17

apparently, `profile` exists (or the error would be something like no "id" in `undefined`) but `profile.id` does not.

This profile comes from passport and should contain the info from the user profile url (or https://keycloak.example.com/auth/realms/test-realm/protocol/openid-connect/userinfo in your example). This response from that URL must be JSON and apparently it also must have a key `id`.

I am not familiar with Keycloak beyond what's on its Wikipedia page. Could you check and post the output of the profile url? Perhaps we can work with that.

**Comment by boardfish** [comment]
```
{"sub":"<user ID from Keycloak>","email_verified":true,"name":"Simon Fish","preferred_username":"boardfish","given_name":"Simon","family_name":"Fish","email":"si@mon.fish"}
```

as retrieved from `curl -v https://keycloak.example.com/auth/realms/test-realm/protocol/openid-connect/userinfo -d access_token=$TOKEN`

If there's a way for me to mirror `sub` to `id` for the benefit of CodiMD, I can use that to mitigate this. Otherwise, it'd be good to allow specifying the name of the ID field in config, as with the rest of the generic OAuth details.

**Comment by boardfish** [comment]
I was able to add `id` to the `userinfo` response:

```
{"sub":"<user ID from keycloak>","website":"simon.fish","email_verified":true,"name":"Simon Fish","id":<user ID from keycloak>","preferred_username":"boardfish","given_name":"Simon","family_name":"Fish","email":"si@mon.fish"}
```

However, I'm still receiving the same error, referring to the same line.

As an aside, I was able to do this in Keycloak by adding a client scope mapper through Client Scopes, referring to the user property `id`, then assigning this scope to the client I'm using for CodiMD.

**Comment by boardfish** [comment]
Fixing up other attributes that should be loaded in from environment variables mitigated my issues. Config is as follows:

```
CMD_OAUTH2_USER_PROFILE_USERNAME_ATTR=preferred_username
CMD_OAUTH2_USER_PROFILE_DISPLAY_NAME_ATTR=name
CMD_OAUTH2_USER_PROFILE_EMAIL_ATTR=email
```

I don't suggest sweeping code changes should be made in order to mitigate this, but error handling that's more indicative of incorrectly set environment variables would be a boon. The ability to change the name of the field CodiMD uses for ID, instead of having to create a client scope mapper, might also be good. I'll close this for now and open a new issue suggesting these features.
