### ISSUE TITLE
Is there a way to unpublish a Note?

### ISSUE THREAD

**Issue by autra** [codimd/server#570]
Say I don't want an note to be public, but clicked on "publish" by error. Can I unpublish it?

**Comment by davidmehren** [comment]
Notes are always "published" as in they are always accessible by the "publish link" regardless of having pressed the button. Access is controlled in the same way it is for notes: the URL is random and can't be guessed.

**Comment by SISheogorath** [comment]
Please not you can restrict access to your note, using the note permissions:

![image](https://user-images.githubusercontent.com/8719867/99107684-804a7080-25e6-11eb-9996-fb720890cae9.png)

**Comment by autra** [comment]
Ok, I didn't understand that accessing via "public link" still checks the permissions. All good for me then, thanks for your explanations :-)
