### ISSUE TITLE
Remove legacy code path for noteId in socket io connections

### ISSUE THREAD

**Issue by ccoenen** [codimd/server#58]
socket-io used to use the referer field to determine the note-id. This was changed over a year ago towards the query part of the url. A backwards compatibility was left in place. I think it's time to remove that.

https://github.com/codimd/server/blob/321114db120c55885bee4dcbb66134f305733be6/lib/realtime.js#L280-L289

This was originally discussed in https://github.com/hackmdio/codimd/issues/623 and changed in https://github.com/codimd/server/commit/c4f8fb78eeef1c9536caae4c8cced4f0f50f1932

**Comment by Amolith** [comment]
I can take a look at this one!
