### ISSUE TITLE
Toolbar, File Upload Button feedback

### ISSUE THREAD

**Issue by ccoenen** [codimd/server#63]
Most of the things in #23 are completed, but I think this deserves its own issue:

> [...] the label changes to the last chosen file's name. Not sure whether this is intended, but I guess it's due to the `<input type="file">`.
And you get no response if the chosen file type is not supported.

_Originally posted by @HerHde in https://github.com/codimd/server/issues/23#issuecomment-479668185_

**Comment by SISheogorath** [comment]
@ccoenen isn't that fix with the recent toolbar styling?

**Comment by ccoenen** [comment]
I'm not sure what is meant with "the label changes to the last chosen file's name". Either that has been fixed, or I'm just not seeing what label is described here. I would like to ask @HerHde to check this on https://demo.codimd.org/

What is _not_ yet completed is the missing feedback with unsupported filetypes. If I upload a spreadsheet instead of an image, nothing happens (no error, no success, nothing). And this should definitely be improved.

**Comment by ccoenen** [comment]
I can't really see a problem with the upload button, I'm closing this for now. Feel free to comment on this and I'll reopen it.

**Comment by HerHde** [comment]
Just to complete this:
I can't reproduce the problem any more, so yeah, I guess it's fixed.
