### ISSUE TITLE
Exclude tags (especially images) from document name

### ISSUE THREAD

**Issue by lhw** [codimd/server#69]
I recently tried adding a small logo to one of my documents with the ![]() syntax and while that works flawlessly I also noticed that this would display the un-interpreted line as the "document name" in the personal history. That basically makes the title unreadable. Other common markdown tags such as italic, bold etc are already ignored as far as I can tell.

So my feature request would be to remove interpretable tags from the header alltogether.

**Comment by ccoenen** [comment]
we _should_ add the alt text instead if any is given (in my opinion).

**Comment by lhw** [comment]
Yes. That would be a good solution i'd say.

**Comment by lhw** [comment]
Closed in https://github.com/codimd/react-client/pull/616
