### ISSUE TITLE
Presentation mode not working in 1.3.2?

### ISSUE THREAD

**Issue by ttasovac** [codimd/server#75]
I've recently updated to 1.3.2 and I'm running CodiMD from a Docker container (from a custom-built image; with only a couple of configuration changes in `config.json`). The presentation mode is _not_ working for me an any more. The example slides that come with CodiMD, for instance, are stuck on the first slide with a (quite disturbing Parks&Rec :smiley:) gif in the background repeating itself. 

See [here](http://tacheles.humanistika.org/p/60lPn9O_V#/).

The console reports different errors in Safari and Firefox. In Safari:

```
[Error] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (60lPn9O_V, line 0)

[Error] Refused to load data:text/css;charset=utf-8;base64,Y2xvdWRmbGFyZS1hcHBbYXBwLWlkPSJhLWJldHRlci1icm93c2VyIl0gewogIGRpc3BsYXk6IGJsb2NrOwogIGJhY2tncm91bmQ6ICM0NTQ4NGQ7CiAgY29sb3I6ICNmZmY7CiAgbGluZS1oZWlnaHQ6IDEuNDU7CiAgcG9zaXRpb246IGZpeGVkOwogIHotaW5kZXg6IDkwMDAwMDAwOwogIHRvcDogMDsKICBsZWZ0OiAwOwogIHJpZ2h0OiAwOwogIHBhZGRpbmc6IC41ZW0gMWVtOwogIHRleHQtYWxpZ246IGNlbnRlcjsKICAtd2Via2l0LXVzZXItc2VsZWN0OiBub25lOwogICAgIC1tb3otdXNlci1zZWxlY3Q6IG5vbmU7CiAgICAgIC1tcy11c2VyLXNlbGVjdDogbm9uZTsKICAgICAgICAgIHVzZXItc2VsZWN0OiBub25lOwp9Cgpj...RlcjsKICBmb250LXNpemU6IDEuNWVtOwogIHBvc2l0aW9uOiBhYnNvbHV0ZTsKICByaWdodDogLjRlbTsKICB0b3A6IC4zNWVtOwogIGhlaWdodDogMWVtOwogIHdpZHRoOiAxZW07CiAgbGluZS1oZWlnaHQ6IDE7Cn0KCmNsb3VkZmxhcmUtYXBwW2FwcC1pZD0iYS1iZXR0ZXItYnJvd3NlciJdIGNsb3VkZmxhcmUtYXBwLWNsb3NlOmFjdGl2ZSB7CiAgLXdlYmtpdC10cmFuc2Zvcm06IHRyYW5zbGF0ZVkoMXB4KTsKICAgICAgICAgIHRyYW5zZm9ybTogdHJhbnNsYXRlWSgxcHgpOwp9CgpjbG91ZGZsYXJlLWFwcFthcHAtaWQ9ImEtYmV0dGVyLWJyb3dzZXIiXSBjbG91ZGZsYXJlLWFwcC1jbG9zZTpob3ZlciB7CiAgb3BhY2l0eTogLjllbTsKICBjb2xvcjogI2ZmZjsKfQo= because it does not appear in the style-src directive of the Content Security Policy.
```
and in Firefox, only the latter.

I've played with the Content Security Policy in Nginx, and, for instance, I managed to get rid of these errors by using `proxy_hide_header   "content-security-policy";` and setting up a very permissive CSP in the `/location` but that did _not_ resolve the issue with the slides: even with no errors being reported in the console, the slides were still not working.

I am really at a loss about how to troubleshoot this. I absolutely love CodiMD so I would really appreciate any tips or ideas about how to proceed here.

Many thanks in advance.

**Comment by SISheogorath** [comment]
I did some checking and it seems like there is something involved that is not from CodiMD itself. There is some script loaded from `http://tacheles.humanistika.org/cdn-cgi/apps/body/bAQX1EDKeDL5KcSw30iQOrSUa4k.js` and CodiMD doesn't have a `cdn-cgi` path.

You may "optimize" something that now breaks CodiMD. This should be solved by either disabling this for CodiMD by yourself, talking to your hoster or switching the hosting platform. Either way, it seems like the vanilla version of CodiMD is fine (on https://demo.codimd.org and similar) and it seems to be caused by some "optimization" magic on your server or a middleware/-box that tries to provide smart CDN functionality and improvements.

**Comment by ccoenen** [comment]
There have also been instances of ISPs injecting stuff into websites. Although I haven't seen this with TLS enabled (so far).

**Comment by ttasovac** [comment]
I can't thank you enough for your tips!

The culprit turned out to be Cloudflare. Disabling it on the subdomain where I host CodiMD cured my slides of their (and, increasingly, my very own) psychosis.

I really appreciate your help. And all the work you do on CodiMD.
