### ISSUE TITLE
broken dependency js-sequence-diagrams in 1.32

### ISSUE THREAD

**Issue by CHBMB** [codimd/server#78]
Hi, 

I can see this has been fixed in `master` and on testing I can confirm this, however the [latest release, 1.32](https://github.com/codimd/server/releases/tag/1.3.2) is still affected, having been produced prior to the merge.

[This is the PR that fixes the issue.](https://github.com/codimd/server/commit/1f5515044146e3195f28fb4a14841b23acb4d26a)

Is there any chance you could push a new release so at least when people are grabbing the latest release it works?  Seems less than ideal to have a non-working release to me.

Love the project!

Thanks

This has also been requested [here](https://github.com/hackmdio/codimd/issues/1187)

**Comment by SISheogorath** [comment]
I'm already on my way to prepare 1.4.0 it just took way longer than I expected for various reasons. I hope I can get things ready during this weekend :)

**Comment by CHBMB** [comment]
Oh wow, awesome, thanks @SISheogorath

**Comment by CHBMB** [comment]
@SISheogorath Thanks for the new release.  Going to close this as it's resolved.
