### ISSUE TITLE
styling slides in markdown view-mode (not slide mode)

### ISSUE THREAD

**Issue by ttasovac** [codimd/server#79]
I've noticed that there is room for improvement in the way slides are HTML-previewed in CodiMD (as opposed to how they're shown in the actual reveal.js slide mode), for example the way lists and bullets are centered or the fact that notes (which should be hidden on a slide) appear as text (see below). I find this very distracting when working on a presentation.

I would like to customize this and perhaps offer it as PR should there be interest. Before I do that, it would be good to know:

1. is there a particular reason this hasn't been done before? Would anybody be against, for instance, hiding notes in the HTML-view of Markdown slides?
2. is `index.css` the logical place to add `aside.notes {display:none;}` in? 

<img width="1470" alt="Скриншот 2019-05-25 16 38 34" src="https://user-images.githubusercontent.com/5304839/58370850-986a9380-7f0b-11e9-9434-3726c1290a7c.png">

**Comment by SISheogorath** [comment]
The right place to add this would be the [./public/css/slide-preview.css](https://github.com/codimd/server/blob/master/public/css/slide-preview.css) and we would really welcome every improvement there.

There is definitely no more particular reason that his hasn't been done yet, besides "lack of time/people who worked on it". If you need any help, feel free to reach out!

If you want to discuss things a bit more interactively, feel free to join our [Matrix](https://matrix.org) community channel at: https://riot.im/app/#/room/#codimd:matrix.org

**Comment by ttasovac** [comment]
Ok, I've worked on this today and I fixed a bunch of things (styling of lists, hiding notes, removing border bottom for h1 and h2, making tables look similar to what they will look like in presentation mode etc.).  For instance:

<img width="899" alt="Скриншот 2019-05-26 16 53 15" src="https://user-images.githubusercontent.com/5304839/58383425-dc769a80-7fd6-11e9-8e46-198e56579952.png">

I haven't made a pull request yet because, when I merged my commits with upstream changes, I realized that the day and night modes now work differently than before.  Namely, it used to be (and is still the case on demo.codimd.org) that the background-color of the view area for slides (as opposed to regular markdown files) is always black, in both day and night modes, as the above image shows.

Now, the background-color of the view areas for slides is affected by the day and night modes. As a result, you can no longer see separate slides in day mode (because they're white on white):

<img width="1030" alt="Скриншот 2019-05-26 17 09 10" src="https://user-images.githubusercontent.com/5304839/58383598-07fa8480-7fd9-11e9-8110-36988e85467c.png">

I just wanted to check whether this change was intended or not. If yes, I guess I can add borders to slides in day mode, although I don't think that will look as good as white slides against a black background.

**Comment by SISheogorath** [comment]
Nice, that looks really good already :+1: Ĺooking forward to see the changes as PR ^^

The changes done by day/night mode are definitely not intended. I don't mind if you consider fixing this too much work, but if you want to fix that, I'll definitely welcome it and get things merged.

**Comment by davidmehren** [comment]
Should already be fixed with #93
