### ISSUE TITLE
Portion of the last text line hidden by the bottom editor bar

### ISSUE THREAD

**Issue by Amolith** [codimd/server#80]
The bottom half of the last line of text is hidden by the bottom bar when using the `Both` view and the `Edit` view

![image](https://user-images.githubusercontent.com/29460675/58370713-9c7cbe00-7ed7-11e9-902b-2699c13ae9d6.png)

**Comment by yusf** [comment]
May this issue be postponed to 1.4.2? Really need #117 to be released.

**Comment by InnayTool** [comment]
I think this issue is fixed in the master branch and in the latest release 1.6.

**Comment by sijanec** [comment]
It is in fact not
